// Native gameplay tags (registered at module load, no .ini needed).
#pragma once

#include "NativeGameplayTags.h"

namespace MTTags
{
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Casting);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Charging);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Staggered);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Countering);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Awakened);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Transforming);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Foresight);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aura);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InQuagmire);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InStorm);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InWindField);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Frozen);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Burning);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_KnowledgeBuff);

	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Beast);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Humanoid);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Monster);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Boss);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Elite);
	MUSHOKURPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NPC_Villager);
}
