"""Writes the "Nature kit" section of Docs/LaPlace/Kit.md from SourceArt/Kit/manifest_nature.json
and QA_nature.json. Only the "## Nature kit" section is replaced (other kits keep their sections);
the file is created if missing. Run by build_nature_kit.py after a full build, or by hand:
    ~/.venvs/mushoku-bpy311/bin/python Tools/kit/nature_docs.py
"""
import fcntl
import json
import os
import re
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
KIT = os.path.join(ROOT, "SourceArt", "Kit")
DOC = os.path.join(ROOT, "Docs", "LaPlace", "Kit.md")
HEADING = "## Nature kit"

REGION_NAMES = {0: "Ocean", 1: "Asura", 2: "Fittoa", 3: "Red Wyrm Mts", 4: "Northern Territories", 5: "Strife Zone",
                6: "Southern Central", 7: "Heaven", 8: "Demon Continent", 9: "Rikarisu", 10: "Great Forest",
                11: "Millis Lowlands", 12: "Blue Wyrm Mts", 13: "Begaritt Desert", 14: "Begaritt Badlands",
                15: "Islands"}


def short_slots(mats):
    return ", ".join(m.replace("MT_", "") for m in mats)


def section(man, qa):
    A = man["assets"]
    by_cat = {}
    for a in A:
        by_cat.setdefault(a["category"], []).append(a)
    tri = {c: sum(a["tris"] for a in v) for c, v in by_cat.items()}
    qa_line = "not run"
    if qa:
        warn = sum(1 for r in qa["results"] if r["warnings"])
        qa_line = "%d / %d assets pass (%d with warnings only)" % (qa["passed"], qa["checked"], warn)
    L = []
    L.append(HEADING)
    L.append("")
    L.append("Procedural nature assets for LA PLACE, generated with Blender 5.0 (`bpy` as a Python module) by "
             "`Tools/kit/build_nature_kit.py`. %d assets: %s. Everything is seeded from the asset name, so a rebuild "
             "reproduces bit-identical GLBs. This section is regenerated by `Tools/kit/nature_docs.py`; edit that "
             "script, not the text." % (len(A), ", ".join("%d %s" % (len(by_cat[c]), c.lower()) for c in
                                                           ("Trees", "Plants", "Rocks") if c in by_cat)))
    L.append("")
    L.append("### Files")
    L.append("")
    L.append("| Path | Content |")
    L.append("|---|---|")
    L.append("| `SourceArt/Kit/Trees/*.glb`, `Plants/*.glb`, `Rocks/*.glb` | one GLB per asset (git-ignored, rebuilt) |")
    L.append("| `SourceArt/Kit/<Category>/_Preview.png` | contact sheet per category (Cycles, 3/4 view, region-tinted ground) |")
    L.append("| `SourceArt/Kit/Trees/_Lineup.png` | all trees side by side at true scale from ~100 m (silhouette / scale check) |")
    L.append("| `SourceArt/Kit/manifest_nature.json` | nature asset list (same schema as `manifest_architecture.json`) |")
    L.append("| `SourceArt/Kit/manifest.json` | shared manifest; nature entries are merged in by name under a file lock |")
    L.append("| `SourceArt/Kit/QA_nature.json` | per-asset QA results (`Tools/kit/qa_nature_kit.py`) |")
    L.append("")
    L.append("Tools: `build_nature_kit.py` (entry point, registry, manifests), `nature_lib.py` (mesh container, tubes, "
             "cards, lathe, remesh / decimate round-trips, export), `nature_trees.py`, `nature_plants.py`, "
             "`nature_rocks.py` (generators), `nature_preview.py` + `nature_textures.py` (preview rendering with "
             "procedural stand-in card textures), `qa_nature_kit.py`, `nature_docs.py`.")
    L.append("")
    L.append("### Rebuild")
    L.append("")
    L.append("```sh")
    L.append("PY=~/.venvs/mushoku-bpy311/bin/python          # Python 3.11 with bpy 5.0, numpy, Pillow")
    L.append("$PY Tools/kit/build_nature_kit.py              # all 74 assets + sheets + manifests + QA + this doc (~4 min)")
    L.append("$PY Tools/kit/build_nature_kit.py --category Rocks")
    L.append("$PY Tools/kit/build_nature_kit.py --only SM_Tree_Oak_A,SM_Rock_Cliff_*   # subset (sheets still show the whole category)")
    L.append("$PY Tools/kit/build_nature_kit.py --no-preview # geometry, manifests and QA only (~20 s)")
    L.append("$PY Tools/kit/build_nature_kit.py --dev /tmp/look --views 3 --only SM_Tree_Giant_A   # look-dev renders, repo untouched")
    L.append("$PY Tools/kit/qa_nature_kit.py [--strict] [names]  # QA only; exit code 1 on failure")
    L.append("```")
    L.append("")
    L.append("### Conventions (Spec sections 6-7)")
    L.append("")
    L.append("- Metres, Blender Z-up (the glTF exporter writes Y-up), one mesh node per file named after the asset, "
             "no node transforms. Slots use the Spec palette names verbatim; each GLB material carries a sensible "
             "base colour only (no textures). Card materials are exported double-sided, solids single-sided.")
    trees = by_cat.get("Trees", [])
    rocks = [a for a in by_cat.get("Rocks", []) if a["kind"] in ("rock", "formation")]
    clumps = [a for a in by_cat.get("Plants", []) if a["kind"] == "groundcover"]
    tz = [-a["min_z"] for a in trees] or [0]
    rz = [100.0 * -a["min_z"] / max(1e-6, a["height"] - a["min_z"]) for a in rocks] or [0]
    cz = [-a["min_z"] for a in clumps] or [0]
    L.append("- Pivot: base centre on the ground (z = 0). Trunks, roots and rocks continue below ground "
             "(`min_z` in the manifest: %.1f-%.1f m for trees, %.0f-%.0f %% of the total height for rocks) so nothing "
             "floats on slopes; ground-cover clumps start %.2f-%.2f m below z = 0." % (
                 min(tz), max(tz), min(rz), max(rz), min(cz), max(cz)))
    L.append("- UVs: rocks and other solids are box-projected at 1 UV = 1 m. Bark is cylindrical: V = metres along "
             "the branch; U wraps an integer number of 1 m tiles on limbs at least 0.75 m round (seamless), and "
             "exactly one metre per metre of circumference on thinner limbs (cone unwrap, seam at the back). Cards "
             "(leaves, needles, palm fronds, grass, wheat, flowers, fern, reeds) cover the whole 0..1 texture with V "
             "pointing up or out along the frond.")
    L.append("- Normals: tree / bush leaf cards carry custom normals blended toward their crown (or canopy-mass) "
             "ellipsoid, giving soft, painterly volume shading; each card's winding is flipped when needed so its "
             "front face agrees with those normals. Grass-type clumps keep geometric normals. Rocks are smooth with "
             "sharp edges above ~40 deg (obsidian crags ~25 deg, flat-faceted).")
    L.append("- Snow is real geometry in `MT_Snow`: pillow sheets along every snow-pine bough, lumps on "
             "`SM_Bush_Snow_A`, a mound under `SM_Grass_Snow_A`, and cap sheets on `SM_Rock_Snow_*` whose edges "
             "tuck under the `MT_RockSnow` surface (no coincident faces). Mossy rocks switch up-facing faces to "
             "`MT_RockMossy`. Palm trunks use `MT_BarkDead` (grey, ringed geometry) and their hanging dead fronds "
             "`MT_GrassDry`, because the palette has no palm bark.")
    L.append("- Budgets: trees 2-10k tris (giants up to 20k), rocks 300-3k, grass / flower / fern / reed / wheat "
             "clumps < 400; bushes and dry scrub 150-2k, giant mushrooms and demon plants 150-3k.")
    L.append("- Manifest extras for placement tools: `regions` (Spec section 3 ids), `scatter` (which world density "
             "map should drive it: `Trees`, `Bushes`, `Grass`, `Flowers`, `Rocks`; `Cliffs` and `Landmark` for "
             "hand / rule placement), `size_range` + `size_rule`, `tris_by_material`, `bounds`, `notes`.")
    L.append("")
    L.append("### QA")
    L.append("")
    L.append("`qa_nature_kit.py` reads every GLB with its own numpy glTF parser (no Blender) and checks: triangle "
             "budget, size range, pivot on the ground at the base centre, no node transforms, slot names in the "
             "palette, no zero-area or degenerate triangles, no loose vertices, no duplicate / coincident "
             "triangles, unit normals that agree with the triangle winding, positive signed volume for solids "
             "(outward normals), solid texel density ~1 UV/m, and card UVs inside and spanning 0..1. "
             "Latest run: **%s**." % qa_line)
    warn_rows = [(r["name"], "; ".join(r["warnings"])) for r in (qa or {}).get("results", []) if r["warnings"]]
    if warn_rows:
        L.append("")
        L.append("Warnings (accepted): " + "; ".join("`%s`: %s" % w for w in warn_rows) + ".")
    L.append("")
    L.append("Budget totals: " + ", ".join("%s %d tris" % (c, tri[c]) for c in ("Trees", "Plants", "Rocks")
                                          if c in tri) + ".")
    for cat in ("Trees", "Plants", "Rocks"):
        if cat not in by_cat:
            continue
        L.append("")
        L.append("### %s (`SourceArt/Kit/%s/`)" % (cat, cat))
        L.append("")
        L.append("| Asset | Size W x D x H (m) | Tris | Slots | Regions | Notes |")
        L.append("|---|---|---:|---|---|---|")
        for a in by_cat[cat]:
            regs = ", ".join(REGION_NAMES.get(r, str(r)) for r in a.get("regions", [])[:4])
            if len(a.get("regions", [])) > 4:
                regs += ", ..."
            L.append("| `%s` | %.1f x %.1f x %.1f | %d | %s | %s | %s |" % (
                a["name"], a["footprint"][0], a["footprint"][1], a["height"], a["tris"], short_slots(a["materials"]),
                regs, a.get("notes", "")))
    L.append("")
    L.append("### Limits and hand-off notes")
    L.append("")
    L.append("- The contact sheets use procedural stand-in textures (leaf clusters, needle sprays, grass blades, "
             "flowers) and procedural bark / rock shading so the cards read as foliage; the game's real textures "
             "(`SourceArt/Textures/T_<Name>_*`) and material instances are mapped by slot name at import.")
    L.append("- Not verified in Unreal from this tool (the engine is not run here): import settings to use are "
             "\"import normals\" (keep the custom foliage normals), two-sided masked materials for the card "
             "slots, and \"combine meshes\" / one static mesh per GLB. No LODs or wind vertex colours are "
             "authored; Nanite or auto-LOD suit the rocks, and foliage wind can key off height or UV V.")
    L.append("- Leaf cards are intersecting quads by design (standard game foliage). Clumps sit at branch tips and "
             "on the crown shell, away from trunks; the exception is the conifers' pair of crossed core cards every "
             "~2 m of trunk, which hug the trunk inside the bough mass so spruces never look hollow from afar.")
    L.append("")
    return "\n".join(L)


def write(man_path=None, qa_path=None):
    man = json.load(open(man_path or os.path.join(KIT, "manifest_nature.json")))
    qp = qa_path or os.path.join(KIT, "QA_nature.json")
    qa = json.load(open(qp)) if os.path.exists(qp) else None
    text = section(man, qa)
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    lock = os.path.join(tempfile.gettempdir(), "laplace_kit_Kit.md.lock")
    with open(lock, "w") as lf:
        fcntl.flock(lf, fcntl.LOCK_EX)
        try:
            doc = open(DOC).read() if os.path.exists(DOC) else ""
            if not doc.strip():
                doc = ("# LA PLACE asset kits\n\nGenerated Blender kits (GLB) for LA PLACE; see "
                       "`Docs/LaPlace/Spec.md` sections 6-7 for the contract. Each kit owns one `##` section, "
                       "maintained by its generator.\n\n")
            m = re.search(r"^## Nature kit[^\n]*\n", doc, flags=re.M)
            if m:
                nxt = re.search(r"^## (?!#)", doc[m.end():], flags=re.M)
                end = m.end() + nxt.start() if nxt else len(doc)
                doc = doc[:m.start()] + text + ("\n" if nxt else "") + doc[end:]
            else:
                doc = doc.rstrip("\n") + "\n\n" + text
            tmp = DOC + ".tmp%d" % os.getpid()
            with open(tmp, "w") as f:
                f.write(doc if doc.endswith("\n") else doc + "\n")
            os.replace(tmp, DOC)
        finally:
            fcntl.flock(lf, fcntl.LOCK_UN)
    print("[nature] wrote the Nature kit section of", os.path.relpath(DOC, ROOT))


if __name__ == "__main__":
    write()
