"""Casting clips of the ability overhaul (Docs/Ability_Overhaul.md §7) for both lineages, on the shared skeleton.

Every element spell has its own clip and silhouette instead of the three generic casts it used to borrow:

  Cast_Fireball (+ _Hold loop, _Release)   right palm up, the fingers cup and turn the sphere while the left hand shapes it
                                          from above; released as a push-toss off the palm
  Cast_FlameWave                          gather at the left hip, one long horizontal sweep of the right arm across the front
  Cast_Inferno        (full body)         right hand raised overhead, clenched, the fist driven down into a crouch
  Cast_WaterBullet                        index and middle finger aimed, snap forward, the fingers kick up (recoil)
  Cast_WaterDragon    (full body)         both hands twirl upward in mirrored rising circles, the body rising, then point
  Cast_Flood          (full body)         both arms gather back (weight back, front foot lifts), stomp and double push forward
  Cast_StoneCannon (+ _Hold, _Release)    right hand forward, fingers claw round the slug, palm thrust, small recoil
  Cast_EarthWall                          crouch, right palm under the earth, driven up above the head
  Cast_EarthSpikes                        right hand raised, driven down and forward along the aim line
  Cast_WindBlade                          knife hand from the left shoulder, one flat fast slash to the right
  Cast_Tornado                            index pointing down, stirring circles that rise, flung up
  Cast_WindBurst                          fists pulled in (compress), arms thrown open (release)

Rudeus's signature upgrades (StoneCannon_Charge / _Hold / _Release: raised hand, compression, braced forearm, palm thrust
and recoil; Quagmire / _Hold / _Release: left palm pressed at the ground; Barrage: 4.6 s of formations, point, paired
directing gestures, converge and push) and Orsted's DisturbMagic and DragonCrush are here too.

Casting hand (the effect's cast socket): the right hand (hand_r) for every element spell, Stone Cannon, Disturb Magic and
Dragon Crush; the left hand (hand_l) for Quagmire; both hands work in Barrage, Flood, Water Dragon and Wind Burst (the right
one points or leads).

Personality (§4). Rudeus's hands shape the magic: fingers curl, fan and roll, wrists turn, energy is gathered and each
release is directed, with recoil after the big ones. Orsted's versions are 55-65% as long, upright, one small gesture of
one hand (an overhead raise stays a raise, a sweep stays a sweep), no crouch except a slight knee bend on the heavy
techniques, and they start and end on his guard.

Timing (§7). Every one-shot starts and ends on the lineage's stance (Rudeus: clips.COMBAT, Orsted: clips_orsted.GUARD),
so montage blends never move a planted foot. The `Release` event is the frame the spell leaves the hand; an
anticipation clip of a chargeable spell ends exactly on its hold loop's first pose, the loop is seamless, and the release
clip starts on that same pose (its `Release` is 0.04 s). Lengths are whole 30 fps frames (F(n)).

How the keys were made: GENERATED by Tools/anim/cast_design/generate.py from hand-target designs (wrist position, palm
normal, finger direction per key, in each lineage's own proportions: cast_design/spells_rudeus.py, spells_orsted.py),
solved into the composer's arm parameters within anatomical ranges by an arm IK design aid (cast_design/armik.py), each key
starting from the previous one so interpolation stays on one branch; then checked on contact sheets and by
qa_animation_quality.py. To change a clip, edit its design (or this file's template, cast_design/clips_spells.template)
and re-run generate.py; hand edits here are overwritten.
New composer parameters used here (pose_compose.DEFAULTS, all 0 by default): <side>_roll (forearm roll, + = palm up),
<side>_fan (fingers spread), <side>_ci / _cm / _cr / _cp (extra curl of index / middle / ring / little finger).
"""
import math

TAU = 2.0 * math.pi
FPS = 30


def F(n):
    """n whole frames at 30 fps: exported lengths and event times line up with the importer's frames."""
    return n / FPS


def _m(*dicts):
    out = {}
    for d in dicts:
        out.update(d)
    return out


def _wave(w, phase):
    """A sine that is 0 at w = 0: hold loops start exactly on their hold pose (the anticipation's last frame)."""
    return math.sin(w + phase) - math.sin(phase)


# ============================================================================================================ Rudeus
# Every delta below is applied on top of clips.COMBAT.
# Fireball held: right palm up, fingers cupped round the sphere, left palm hovering above it
FB_HOLD = {"pel_z": -0.1, "pel_yaw": -16.0, "sp_pitch": 10.0, "sp_yaw": 12.0, "head_pitch": 6.0, "coat_flare": 5.0,
           "hair_lag": 1.0, "R_lower": 34.0, "R_fwd": 65.7, "R_elbow": 74.3, "R_roll": 95.0, "R_wpitch": 2.9,
           "R_wyaw": 15.4, "R_curl": 40.0, "R_fan": 10.0, "R_thumb": 28.0, "L_lower": -17.9, "L_fwd": 55.6,
           "L_elbow": 103.1, "L_roll": 10.5, "L_wpitch": -11.4, "L_wyaw": -25.2, "L_curl": 34.0, "L_fan": 8.0,
           "L_thumb": 20.0}
# Stone Cannon (element) held: right hand forward at the chest, palm to the target, fingers clawed
SCS_HOLD = {"pel_z": -0.1, "pel_yaw": -16.0, "sp_pitch": 9.0, "sp_yaw": 11.0, "coat_flare": 5.0, "R_lower": 9.1,
            "R_fwd": 62.3, "R_elbow": 64.9, "R_roll": -38.0, "R_wpitch": -70.0, "R_wyaw": -16.0, "R_curl": 58.0,
            "R_fan": 4.0, "R_thumb": 40.0}
# Signature Stone Cannon held: right hand raised, fingers and wrist compressed, left hand bracing the forearm
SC_HOLD = {"pel_z": -0.12, "pel_yaw": -17.0, "sp_pitch": 9.0, "sp_yaw": 14.0, "head_pitch": 2.0, "coat_flare": 6.0,
           "R_lower": -30.5, "R_fwd": 38.2, "R_elbow": 75.7, "R_roll": -12.0, "R_wpitch": -70.0, "R_wyaw": -22.2,
           "R_curl": 64.0, "R_fan": -4.0, "R_thumb": 46.0, "L_lower": 6.6, "L_fwd": 106.3, "L_elbow": 70.5,
           "L_roll": 90.9, "L_wpitch": -60.4, "L_curl": 58.0, "L_thumb": 40.0}
# Quagmire held: deep crouch, left palm pressed flat toward the ground, fingers spread
QG_HOLD = {"pel_z": -0.26, "pel_yaw": -12.0, "sp_pitch": 34.0, "sp_yaw": 4.0, "head_pitch": -12.0, "coat_flare": 9.0,
           "R_lower": 8.2, "R_fwd": -51.2, "R_elbow": 126.5, "R_roll": -2.8, "R_wpitch": -26.6, "R_curl": 26.0,
           "R_fan": 6.0, "R_thumb": 14.0, "L_lower": 25.4, "L_fwd": 74.3, "L_elbow": 8.2, "L_roll": 3.3,
           "L_wpitch": -61.4, "L_wyaw": 2.9, "L_curl": 2.0, "L_fan": 22.0, "L_thumb": 10.0}

R_KEYS = {
    "Cast_Fireball": (F(10), [
        (0.000, {}),
        (0.130, {"pel_z": -0.095, "pel_yaw": -15.0, "sp_pitch": 8.0, "sp_yaw": 10.0, "head_pitch": 3.0,
                  "coat_flare": 4.5, "R_lower": 39.5, "R_fwd": 55.0, "R_elbow": 60.9, "R_roll": 49.5,
                  "R_wpitch": -16.7, "R_wyaw": 13.0, "R_curl": 4.0, "R_fan": 18.0, "R_thumb": 10.0, "L_lower": 14.4,
                  "L_fwd": 35.9, "L_elbow": 112.8, "L_roll": -7.5, "L_wpitch": -11.4, "L_wyaw": -20.7, "L_curl": 18.0,
                  "L_fan": 14.0}),
        (0.250, FB_HOLD),
        (F(10), FB_HOLD),
    ]),
    "Cast_Fireball_Release": (F(17), [
        (0.000, FB_HOLD),
        (0.100, {"pel_y": -0.015, "pel_z": -0.1, "pel_yaw": -8.0, "sp_pitch": 13.0, "sp_yaw": -2.0,
                  "head_pitch": 2.0, "coat_trail": 6.0, "hair_lag": 4.0, "R_lower": -2.1, "R_fwd": 99.0,
                  "R_elbow": 9.5, "R_roll": 95.0, "R_wpitch": -7.5, "R_wyaw": 1.4, "R_curl": 6.0, "R_fan": 18.0,
                  "R_thumb": 14.0, "L_lower": 25.0, "L_fwd": 22.5, "L_elbow": 140.0, "L_roll": -11.1,
                  "L_wpitch": -19.4, "L_wyaw": -19.2, "L_thumb": 16.0}),
        (0.170, {"pel_y": -0.02, "pel_z": -0.1, "pel_yaw": -7.0, "sp_pitch": 14.0, "sp_yaw": -3.0, "head_pitch": 2.0,
                  "coat_trail": 5.0, "hair_lag": 4.0, "R_lower": -8.4, "R_fwd": 99.9, "R_elbow": 8.8, "R_roll": 95.0,
                  "R_wpitch": 10.4, "R_wyaw": 14.8, "R_curl": 2.0, "R_fan": 20.0, "R_thumb": 12.0, "L_lower": 25.0,
                  "L_fwd": 22.5, "L_elbow": 140.0, "L_roll": -11.1, "L_wpitch": -19.4, "L_wyaw": -19.2,
                  "L_thumb": 16.0}),
        (0.280, {"pel_y": 0.01, "pel_z": -0.095, "pel_yaw": -10.0, "sp_pitch": 3.0, "sp_yaw": 2.0,
                  "coat_trail": -2.0, "hair_lag": -2.0, "R_lower": 2.6, "R_fwd": 72.3, "R_elbow": 41.4,
                  "R_roll": 95.0, "R_wpitch": 0.0, "R_wyaw": 22.0, "R_curl": 14.0, "R_fan": 10.0, "R_thumb": 12.0,
                  "L_lower": 71.2, "L_fwd": 4.4, "L_elbow": 115.4, "L_roll": -18.5, "L_wpitch": -9.4, "L_wyaw": -18.3,
                  "L_thumb": 16.0}),
        (F(17), {}),
    ]),
    "Cast_FlameWave": (F(30), [
        (0.000, {}),
        (0.160, {"pel_z": -0.13, "pel_yaw": -2.0, "sp_pitch": 10.0, "sp_yaw": 26.0, "head_yaw": -18.0,
                  "coat_flare": 6.0, "hair_lag": 2.0, "R_lower": 36.5, "R_fwd": 94.3, "R_elbow": 51.7, "R_roll": -7.8,
                  "R_wpitch": -25.6, "R_wyaw": 1.4, "R_curl": 26.0, "R_fan": 6.0, "R_thumb": 16.0, "L_lower": 76.5,
                  "L_fwd": -11.4, "L_elbow": 106.2, "L_roll": -31.5, "L_wpitch": 1.9, "L_thumb": 14.0}),
        (0.320, {"pel_z": -0.12, "pel_yaw": -8.0, "sp_pitch": 10.0, "sp_yaw": 14.0, "head_yaw": -8.0,
                  "coat_flare": 6.0, "R_lower": 8.0, "R_fwd": 111.0, "R_elbow": 9.3, "R_roll": -17.4,
                  "R_wpitch": -41.3, "R_wyaw": 5.1, "R_curl": 8.0, "R_fan": 14.0, "R_thumb": 12.0, "L_lower": 76.5,
                  "L_fwd": -11.4, "L_elbow": 106.2, "L_roll": -31.5, "L_wpitch": 1.9, "L_thumb": 14.0}),
        (0.420, {"pel_z": -0.11, "sp_pitch": 11.0, "sp_yaw": 0.0, "head_yaw": 0.0, "coat_trail": 4.0,
                  "coat_flare": 7.0, "hair_lag": 4.0, "R_lower": 1.9, "R_fwd": 101.1, "R_elbow": 8.0, "R_roll": -8.3,
                  "R_wpitch": -32.7, "R_wyaw": -6.9, "R_curl": 2.0, "R_fan": 20.0, "R_thumb": 10.0, "L_lower": 76.5,
                  "L_fwd": -11.4, "L_elbow": 106.2, "L_roll": -31.5, "L_wpitch": 1.9, "L_thumb": 14.0}),
        (0.540, {"pel_z": -0.11, "pel_yaw": -20.0, "sp_pitch": 9.0, "sp_yaw": -16.0, "head_yaw": 10.0,
                  "coat_trail": 3.0, "coat_flare": 8.0, "hair_lag": 3.0, "R_lower": -0.1, "R_fwd": 70.8,
                  "R_elbow": 10.7, "R_roll": 13.6, "R_wpitch": -36.3, "R_wyaw": -14.5, "R_curl": 2.0, "R_fan": 22.0,
                  "R_thumb": 10.0, "L_lower": 79.0, "L_fwd": -70.0, "L_elbow": 119.0, "L_roll": -30.5,
                  "L_wpitch": 9.4, "L_thumb": 14.0}),
        (0.660, {"pel_z": -0.105, "pel_yaw": -19.0, "sp_pitch": 8.0, "sp_yaw": -14.0, "head_yaw": 8.0,
                  "coat_flare": 6.0, "R_lower": 9.0, "R_fwd": 69.6, "R_elbow": 11.0, "R_roll": 23.8,
                  "R_wpitch": -40.1, "R_wyaw": -16.3, "R_curl": 14.0, "R_fan": 12.0, "R_thumb": 12.0, "L_lower": 79.0,
                  "L_fwd": -70.0, "L_elbow": 119.0, "L_roll": -30.5, "L_wpitch": 9.4, "L_thumb": 14.0}),
        (F(30), {}),
    ]),
    "Cast_Inferno": (F(48), [
        (0.000, {}),
        (0.240, {"pel_y": 0.01, "pel_z": -0.07, "sp_pitch": 2.0, "sp_yaw": 6.0, "coat_flare": 5.0, "R_lower": -35.2,
                  "R_fwd": 50.5, "R_elbow": 79.4, "R_roll": -78.2, "R_wpitch": -2.2, "R_wyaw": -7.6, "R_fan": 16.0,
                  "R_thumb": 12.0, "L_lower": 48.5, "L_fwd": -33.5, "L_elbow": 69.5, "L_roll": -28.1,
                  "L_wpitch": -12.7, "L_curl": 16.0, "L_fan": 10.0}),
        (0.460, {"pel_y": 0.03, "pel_z": -0.04, "sp_pitch": -6.0, "sp_yaw": 4.0, "head_pitch": -16.0,
                  "coat_flare": 7.0, "hair_lag": -3.0, "R_lower": -59.4, "R_fwd": 88.2, "R_elbow": 13.2,
                  "R_roll": -32.7, "R_wpitch": -43.2, "R_wyaw": -18.9, "R_curl": 5.0, "R_fan": 22.0, "R_thumb": 10.0,
                  "L_lower": 49.6, "L_fwd": -24.0, "L_elbow": 35.3, "L_roll": -33.8, "L_wpitch": -29.4,
                  "L_curl": 16.0, "L_fan": 12.0}),
        (0.580, {"pel_y": 0.03, "pel_z": -0.035, "sp_pitch": -7.0, "sp_yaw": 4.0, "head_pitch": -17.0,
                  "coat_flare": 7.0, "hair_lag": -3.0, "R_lower": -56.8, "R_fwd": 84.7, "R_elbow": 16.9,
                  "R_roll": -7.1, "R_wpitch": -55.0, "R_wyaw": -18.5, "R_curl": 96.0, "R_fan": -4.0, "R_thumb": 62.0,
                  "L_lower": 49.6, "L_fwd": -24.0, "L_elbow": 35.3, "L_roll": -33.8, "L_wpitch": -29.4,
                  "L_curl": 16.0, "L_fan": 12.0}),
        (0.760, {"pel_y": -0.01, "pel_z": -0.12, "sp_pitch": 12.0, "sp_yaw": 0.0, "head_pitch": -2.0,
                  "coat_flare": 8.0, "hair_lag": 2.0, "R_lower": -38.1, "R_fwd": 83.3, "R_elbow": 47.0,
                  "R_roll": -7.1, "R_wpitch": -55.0, "R_wyaw": -18.1, "R_curl": 96.0, "R_fan": -4.0, "R_thumb": 62.0,
                  "L_lower": 56.1, "L_fwd": -70.0, "L_elbow": 48.2, "L_roll": -31.9, "L_wpitch": -30.2,
                  "L_curl": 24.0, "L_fan": 12.0, "L_thumb": 14.0}),
        (0.900, {"pel_y": -0.05, "pel_z": -0.27, "sp_pitch": 30.0, "sp_yaw": -4.0, "head_pitch": -10.0,
                  "coat_trail": 6.0, "coat_flare": 10.0, "hair_lag": 6.0, "R_lower": 8.9, "R_fwd": 86.0,
                  "R_elbow": 59.5, "R_roll": 12.9, "R_wpitch": -32.7, "R_wyaw": -21.8, "R_curl": 96.0, "R_fan": -4.0,
                  "R_thumb": 62.0, "L_lower": 30.4, "L_fwd": -70.0, "L_elbow": 4.7, "L_roll": -54.4,
                  "L_wpitch": -45.5, "L_fan": 12.0, "L_thumb": 16.0}),
        (1.100, {"pel_y": -0.045, "pel_z": -0.25, "sp_pitch": 27.0, "sp_yaw": -3.0, "head_pitch": -8.0,
                  "coat_flare": 8.0, "hair_lag": 3.0, "R_lower": 10.2, "R_fwd": 82.5, "R_elbow": 61.0, "R_roll": 25.4,
                  "R_wpitch": -18.4, "R_wyaw": -22.3, "R_curl": 96.0, "R_fan": -4.0, "R_thumb": 62.0, "L_lower": 30.4,
                  "L_fwd": -70.0, "L_elbow": 4.7, "L_roll": -54.4, "L_wpitch": -45.5, "L_fan": 12.0, "L_thumb": 16.0}),
        (F(48), {}),
    ]),
    "Cast_WaterBullet": (F(18), [
        (0.000, {}),
        (0.110, {"pel_yaw": -17.0, "sp_pitch": 8.0, "sp_yaw": 12.0, "head_pitch": -3.0, "R_lower": 12.5,
                  "R_fwd": 31.7, "R_elbow": 105.0, "R_roll": 14.9, "R_wpitch": -38.3, "R_wyaw": 0.2, "R_curl": 82.0,
                  "R_fan": -5.0, "R_thumb": 50.0, "R_ci": -84.0, "R_cm": -86.0}),
        (0.220, {"pel_yaw": -10.0, "sp_pitch": 10.0, "sp_yaw": 4.0, "coat_trail": 3.0, "hair_lag": 2.0,
                  "R_lower": -6.1, "R_fwd": 63.2, "R_elbow": 66.4, "R_roll": 46.9, "R_wpitch": -33.4, "R_wyaw": -12.6,
                  "R_curl": 82.0, "R_fan": -5.0, "R_thumb": 50.0, "R_ci": -84.0, "R_cm": -86.0}),
        (0.290, {"pel_yaw": -11.0, "sp_yaw": 5.0, "head_pitch": -5.0, "hair_lag": -1.0, "R_lower": -10.7,
                  "R_fwd": 59.0, "R_elbow": 70.9, "R_roll": 54.0, "R_wpitch": -41.2, "R_wyaw": 6.7, "R_curl": 82.0,
                  "R_fan": -5.0, "R_thumb": 50.0, "R_ci": -84.0, "R_cm": -86.0}),
        (0.420, {"pel_yaw": -13.0, "sp_yaw": 8.0, "R_lower": 19.1, "R_fwd": 49.6, "R_elbow": 64.4, "R_roll": 54.0,
                  "R_wpitch": -41.2, "R_wyaw": 6.7, "R_curl": 40.0, "R_thumb": 24.0, "R_ci": -20.0, "R_cm": -20.0}),
        (F(18), {}),
    ]),
    "Cast_WaterDragon": (F(45), [
        (0.000, {}),
        (0.100, {"pel_z": -0.14, "sp_pitch": 8.0, "head_pitch": 4.0, "coat_flare": 5.0, "R_lower": 44.4,
                  "R_fwd": 42.2, "R_elbow": 89.5, "R_roll": 20.4, "R_wpitch": -31.6, "R_wyaw": 0.5, "R_curl": 24.0,
                  "R_fan": 12.0, "R_thumb": 14.0, "L_lower": 56.9, "L_fwd": 20.8, "L_elbow": 96.9, "L_roll": 18.2,
                  "L_wpitch": -19.1, "L_wyaw": 1.8, "L_curl": 24.0, "L_fan": 12.0, "L_thumb": 14.0}),
        (0.190, {"pel_z": -0.12, "sp_pitch": 5.6, "sp_yaw": 4.0, "head_pitch": 0.8, "coat_flare": 5.8,
                  "hair_lag": -0.4, "R_lower": 14.3, "R_fwd": 54.0, "R_elbow": 69.9, "R_roll": 23.6,
                  "R_wpitch": -47.5, "R_wyaw": 10.8, "R_curl": 22.0, "R_fan": 14.0, "R_thumb": 14.0, "L_lower": 22.0,
                  "L_fwd": 20.5, "L_elbow": 87.9, "L_roll": 23.5, "L_wpitch": -37.4, "L_wyaw": 11.4, "L_curl": 22.0,
                  "L_fan": 14.0, "L_thumb": 14.0}),
        (0.280, {"pel_z": -0.1, "sp_pitch": 3.2, "sp_yaw": 0.0, "head_pitch": -2.4, "coat_flare": 6.6,
                  "hair_lag": -0.8, "R_lower": 2.8, "R_fwd": 34.7, "R_elbow": 87.7, "R_roll": 26.7, "R_wpitch": -57.7,
                  "R_wyaw": 11.7, "R_curl": 22.0, "R_fan": 14.0, "R_thumb": 14.0, "L_lower": 9.8, "L_fwd": -11.8,
                  "L_elbow": 107.7, "L_roll": 28.0, "L_wpitch": -49.2, "L_wyaw": 12.2, "L_curl": 22.0, "L_fan": 14.0,
                  "L_thumb": 14.0}),
        (0.370, {"pel_z": -0.08, "sp_pitch": 0.8, "sp_yaw": -4.0, "head_pitch": -5.6, "coat_flare": 7.4,
                  "hair_lag": -1.2, "R_lower": -19.8, "R_fwd": 33.6, "R_elbow": 111.8, "R_roll": 34.5,
                  "R_wpitch": -61.4, "R_wyaw": 10.6, "R_curl": 22.0, "R_fan": 14.0, "R_thumb": 14.0, "L_lower": -26.6,
                  "L_fwd": -25.9, "L_elbow": 135.5, "L_roll": 36.6, "L_wpitch": -60.9, "L_wyaw": 10.7, "L_curl": 22.0,
                  "L_fan": 14.0, "L_thumb": 14.0}),
        (0.460, {"pel_z": -0.06, "sp_pitch": -1.6, "sp_yaw": 0.0, "head_pitch": -8.8, "coat_flare": 8.2,
                  "hair_lag": -1.6, "R_lower": -30.8, "R_fwd": 58.3, "R_elbow": 83.7, "R_roll": 43.7,
                  "R_wpitch": -61.2, "R_wyaw": 9.5, "R_curl": 22.0, "R_fan": 14.0, "R_thumb": 14.0, "L_lower": -47.7,
                  "L_fwd": 13.2, "L_elbow": 106.3, "L_roll": 48.5, "L_wpitch": -62.9, "L_wyaw": 5.9, "L_curl": 22.0,
                  "L_fan": 14.0, "L_thumb": 14.0}),
        (0.550, {"pel_z": -0.04, "sp_pitch": -4.0, "sp_yaw": 4.0, "head_pitch": -12.0, "coat_flare": 9.0,
                  "hair_lag": -2.0, "R_lower": -27.9, "R_fwd": 74.2, "R_elbow": 27.7, "R_roll": 47.7,
                  "R_wpitch": -55.0, "R_wyaw": 11.1, "R_curl": 22.0, "R_fan": 14.0, "R_thumb": 14.0, "L_lower": -35.3,
                  "L_fwd": 35.5, "L_elbow": 56.4, "L_roll": 54.5, "L_wpitch": -58.8, "L_wyaw": 9.7, "L_curl": 22.0,
                  "L_fan": 14.0, "L_thumb": 14.0}),
        (0.620, {"pel_z": -0.04, "sp_pitch": -5.0, "head_pitch": -14.0, "coat_flare": 9.0, "hair_lag": -3.0,
                  "L_fpitch": -8.0, "R_fpitch": -8.0, "R_lower": -49.3, "R_fwd": 65.3, "R_elbow": 40.3,
                  "R_roll": 64.6, "R_wpitch": -49.2, "R_wyaw": 10.6, "R_curl": 12.0, "R_fan": 18.0, "R_thumb": 12.0,
                  "L_lower": -55.3, "L_fwd": 44.2, "L_elbow": 51.3, "L_roll": 71.5, "L_wpitch": -54.3, "L_wyaw": 10.1,
                  "L_curl": 12.0, "L_fan": 18.0}),
        (0.750, {"pel_z": -0.09, "pel_yaw": -20.0, "sp_yaw": 8.0, "head_pitch": 0.0, "coat_trail": 5.0,
                  "coat_flare": 8.0, "hair_lag": 4.0, "L_fpitch": -8.0, "R_fpitch": -8.0, "R_lower": -22.3,
                  "R_fwd": 102.1, "R_elbow": 10.2, "R_roll": 66.8, "R_wpitch": -17.8, "R_wyaw": 7.3, "R_curl": 82.0,
                  "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": -79.6, "L_fwd": -36.0, "L_elbow": 80.2,
                  "L_roll": 79.6, "L_wpitch": -60.1, "L_wyaw": 10.0, "L_curl": 16.0, "L_fan": 14.0}),
        (0.950, {"pel_z": -0.09, "pel_yaw": -19.0, "sp_pitch": 6.0, "sp_yaw": 8.0, "head_pitch": 0.0,
                  "coat_flare": 6.0, "L_fpitch": -8.0, "R_fpitch": -8.0, "R_lower": -18.2, "R_fwd": 99.5,
                  "R_elbow": 9.9, "R_roll": 68.5, "R_wpitch": -9.0, "R_wyaw": 6.5, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 36.5, "L_fwd": -48.0, "L_elbow": 130.7, "L_roll": 79.6,
                  "L_wpitch": -58.4, "L_wyaw": 10.0, "L_curl": 20.0, "L_fan": 8.0}),
        (F(45), {"L_fpitch": -8.0, "R_fpitch": -8.0}),
    ]),
    "Cast_Flood": (F(45), [
        (0.000, {}),
        (0.280, {"pel_y": 0.05, "pel_z": -0.12, "pel_yaw": -8.0, "sp_pitch": -6.0, "sp_yaw": 2.0, "head_pitch": 4.0,
                  "coat_trail": -6.0, "hair_lag": -3.0, "R_lower": 74.0, "R_fwd": -50.5, "R_swing": -48.7,
                  "R_elbow": 107.0, "R_roll": -7.8, "R_wpitch": -28.3, "R_curl": 20.0, "R_fan": 10.0, "R_thumb": 14.0,
                  "L_lower": 90.0, "L_fwd": -58.8, "L_swing": -65.6, "L_elbow": 103.2, "L_roll": -3.4,
                  "L_wpitch": -23.1, "L_curl": 20.0, "L_fan": 10.0, "L_thumb": 14.0}),
        (0.460, {"pel_y": 0.06, "pel_z": -0.12, "pel_yaw": -8.0, "sp_pitch": -10.0, "sp_yaw": 2.0, "head_pitch": 2.0,
                  "coat_trail": -8.0, "hair_lag": -4.0, "L_fz": 0.05, "L_fpitch": 6.0, "R_lower": 56.8,
                  "R_fwd": -64.5, "R_swing": -59.7, "R_elbow": 117.0, "R_roll": 4.6, "R_wpitch": -30.5,
                  "R_curl": 16.0, "R_fan": 14.0, "R_thumb": 12.0, "L_lower": 70.9, "L_fwd": -70.0, "L_swing": -70.0,
                  "L_elbow": 107.8, "L_roll": 7.8, "L_wpitch": -26.9, "L_curl": 16.0, "L_fan": 14.0}),
        (0.610, {"pel_z": -0.17, "pel_yaw": -9.0, "sp_pitch": 12.0, "sp_yaw": 2.0, "head_pitch": -2.0,
                  "coat_trail": 2.0, "hair_lag": 2.0, "L_fz": 0.02, "L_fpitch": 2.0, "R_lower": 51.4, "R_fwd": -13.7,
                  "R_swing": 9.9, "R_elbow": 118.2, "R_roll": -25.3, "R_wpitch": -45.3, "R_wyaw": 11.0, "R_curl": 8.0,
                  "R_fan": 18.0, "R_thumb": 12.0, "L_lower": 64.6, "L_fwd": -33.9, "L_swing": -1.1, "L_elbow": 129.4,
                  "L_roll": -27.0, "L_wpitch": -41.8, "L_wyaw": 11.7, "L_curl": 8.0, "L_fan": 18.0}),
        (0.700, {"pel_y": -0.06, "pel_z": -0.22, "pel_yaw": -10.0, "sp_pitch": 26.0, "sp_yaw": 2.0,
                  "head_pitch": -8.0, "coat_trail": 8.0, "coat_flare": 8.0, "hair_lag": 6.0, "L_fz": 0.02,
                  "L_fpitch": 2.0, "R_lower": 67.7, "R_fwd": 29.6, "R_swing": 50.9, "R_elbow": 83.5, "R_roll": -50.6,
                  "R_wpitch": -41.6, "R_wyaw": -1.1, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0, "L_lower": 72.5,
                  "L_fwd": 5.9, "L_swing": 42.9, "L_elbow": 97.3, "L_roll": -59.1, "L_wpitch": -35.4, "L_wyaw": 1.1,
                  "L_curl": 3.0, "L_fan": 20.0}),
        (0.900, {"pel_y": -0.05, "pel_z": -0.2, "pel_yaw": -10.0, "sp_pitch": 22.0, "sp_yaw": 2.0,
                  "head_pitch": -6.0, "coat_trail": 4.0, "coat_flare": 7.0, "L_fz": 0.02, "L_fpitch": 2.0,
                  "R_lower": 73.9, "R_fwd": 25.8, "R_swing": 50.2, "R_elbow": 72.1, "R_roll": -63.5,
                  "R_wpitch": -45.7, "R_wyaw": -4.5, "R_curl": 8.0, "R_fan": 14.0, "R_thumb": 12.0, "L_lower": 78.0,
                  "L_fwd": 1.7, "L_swing": 41.0, "L_elbow": 87.1, "L_roll": -73.3, "L_wpitch": -39.3, "L_wyaw": -1.7,
                  "L_curl": 8.0, "L_fan": 14.0}),
        (1.120, {"pel_y": -0.02, "pel_z": -0.14, "pel_yaw": -12.0, "sp_pitch": 12.0, "sp_yaw": 5.0,
                  "coat_trail": 2.0, "coat_flare": 5.0, "L_fz": 0.02, "L_fpitch": 2.0, "R_lower": 69.0, "R_fwd": 12.8,
                  "R_swing": 28.3, "R_elbow": 70.4, "R_roll": -63.5, "R_wpitch": -45.7, "R_wyaw": -4.5,
                  "R_curl": 14.0, "R_fan": 6.0, "R_thumb": 10.0, "L_lower": 78.6, "L_fwd": -3.3, "L_swing": 14.0,
                  "L_elbow": 96.1, "L_roll": -73.1, "L_wpitch": -39.3, "L_wyaw": -1.7, "L_curl": 24.0, "L_fan": 4.0}),
        (F(45), {"L_fz": 0.02, "L_fpitch": 2.0}),
    ]),
    "Cast_StoneCannon": (F(11), [
        (0.000, {}),
        (0.180, {"pel_z": -0.095, "pel_yaw": -15.0, "sp_pitch": 8.0, "sp_yaw": 10.0, "R_lower": 11.4, "R_fwd": 59.4,
                  "R_elbow": 66.6, "R_roll": -16.1, "R_wpitch": -70.0, "R_wyaw": 2.6, "R_curl": 24.0, "R_fan": 14.0,
                  "R_thumb": 14.0}),
        (0.300, SCS_HOLD),
        (F(11), SCS_HOLD),
    ]),
    "Cast_StoneCannon_Release": (F(15), [
        (0.000, SCS_HOLD),
        (0.100, {"pel_z": -0.1, "pel_yaw": -9.0, "sp_pitch": 12.0, "sp_yaw": 3.0, "coat_trail": 4.0, "hair_lag": 3.0,
                  "R_lower": -4.1, "R_fwd": 94.4, "R_elbow": 11.3, "R_roll": -33.7, "R_wpitch": -70.0,
                  "R_wyaw": -21.3, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0}),
        (0.190, {"pel_z": -0.1, "pel_yaw": -11.0, "sp_pitch": 6.0, "sp_yaw": 5.0, "head_pitch": -3.0,
                  "hair_lag": -1.0, "R_lower": -6.4, "R_fwd": 85.5, "R_elbow": 24.2, "R_roll": -33.7,
                  "R_wpitch": -70.0, "R_wyaw": -21.8, "R_fan": 12.0, "R_thumb": 12.0}),
        (F(15), {}),
    ]),
    "Cast_EarthWall": (F(27), [
        (0.000, {}),
        (0.200, {"pel_z": -0.2, "sp_pitch": 28.0, "sp_yaw": 8.0, "head_pitch": -8.0, "coat_flare": 6.0,
                  "R_lower": 26.1, "R_fwd": 84.9, "R_elbow": 19.7, "R_roll": 82.8, "R_wpitch": 12.2, "R_wyaw": 21.5,
                  "R_curl": 36.0, "R_fan": 16.0, "R_thumb": 24.0, "L_lower": 55.2, "L_fwd": 43.5, "L_elbow": 48.8,
                  "L_roll": -24.7, "L_wpitch": -44.9, "L_curl": 24.0, "L_thumb": 14.0}),
        (0.400, {"pel_z": -0.09, "sp_pitch": 6.0, "sp_yaw": 6.0, "head_pitch": -2.0, "coat_flare": 7.0,
                  "hair_lag": -2.0, "R_lower": 1.0, "R_fwd": 64.8, "R_elbow": 77.2, "R_roll": 95.0, "R_wpitch": 16.3,
                  "R_wyaw": 22.0, "R_curl": 20.0, "R_fan": 16.0, "R_thumb": 16.0, "L_lower": 85.2, "L_fwd": -49.7,
                  "L_elbow": 73.0, "L_roll": -57.5, "L_wpitch": -30.4, "L_curl": 24.0, "L_thumb": 14.0}),
        (0.560, {"pel_z": -0.06, "sp_pitch": -2.0, "sp_yaw": 5.0, "head_pitch": -8.0, "coat_flare": 8.0,
                  "hair_lag": -3.0, "R_lower": -38.5, "R_fwd": 103.1, "R_elbow": 5.5, "R_roll": 94.1,
                  "R_wpitch": -47.9, "R_wyaw": 12.0, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0, "L_lower": 85.2,
                  "L_fwd": -49.7, "L_elbow": 73.0, "L_roll": -57.5, "L_wpitch": -30.4, "L_curl": 24.0,
                  "L_thumb": 14.0}),
        (0.660, {"pel_z": -0.065, "sp_pitch": -1.0, "sp_yaw": 5.0, "head_pitch": -6.0, "coat_flare": 6.0,
                  "R_lower": -37.5, "R_fwd": 98.5, "R_elbow": 10.9, "R_roll": 90.9, "R_wpitch": -64.7, "R_wyaw": 10.3,
                  "R_fan": 14.0, "R_thumb": 12.0, "L_lower": 85.2, "L_fwd": -49.7, "L_elbow": 73.0, "L_roll": -57.5,
                  "L_wpitch": -30.4, "L_curl": 24.0, "L_thumb": 14.0}),
        (F(27), {}),
    ]),
    "Cast_EarthSpikes": (F(27), [
        (0.000, {}),
        (0.180, {"pel_z": -0.07, "sp_pitch": -2.0, "sp_yaw": 10.0, "coat_flare": 5.0, "R_lower": -52.1,
                  "R_fwd": 18.4, "R_elbow": 90.4, "R_roll": 29.4, "R_wpitch": -26.6, "R_wyaw": -16.0, "R_fan": 16.0,
                  "R_thumb": 12.0}),
        (0.400, {"pel_y": -0.03, "pel_z": -0.2, "sp_pitch": 30.0, "sp_yaw": 2.0, "head_pitch": -10.0,
                  "coat_trail": 5.0, "coat_flare": 7.0, "hair_lag": 5.0, "R_lower": 10.4, "R_fwd": 105.5,
                  "R_elbow": 8.6, "R_roll": 3.2, "R_wpitch": -34.5, "R_wyaw": -13.3, "R_curl": 3.0, "R_fan": 20.0,
                  "R_thumb": 12.0, "L_lower": 44.2, "L_fwd": -70.0, "L_elbow": 68.6, "L_roll": -5.6, "L_wpitch": -9.2,
                  "L_curl": 24.0, "L_thumb": 14.0}),
        (0.520, {"pel_y": -0.03, "pel_z": -0.21, "sp_pitch": 31.0, "sp_yaw": 2.0, "head_pitch": -9.0,
                  "coat_flare": 6.0, "hair_lag": 3.0, "R_lower": 12.2, "R_fwd": 105.6, "R_elbow": 8.1, "R_roll": -7.9,
                  "R_wpitch": -36.9, "R_wyaw": -14.8, "R_curl": 8.0, "R_fan": 18.0, "R_thumb": 12.0, "L_lower": 44.2,
                  "L_fwd": -70.0, "L_elbow": 68.6, "L_roll": -5.6, "L_wpitch": -9.2, "L_curl": 24.0, "L_thumb": 14.0}),
        (F(27), {}),
    ]),
    "Cast_WindBlade": (F(18), [
        (0.000, {}),
        (0.140, {"pel_yaw": -8.0, "sp_pitch": 8.0, "sp_yaw": 20.0, "head_yaw": -12.0, "R_lower": -8.2, "R_fwd": 74.2,
                  "R_elbow": 72.4, "R_roll": -0.2, "R_wpitch": -6.7, "R_wyaw": -11.0, "R_curl": 3.0, "R_fan": -8.0,
                  "R_thumb": 26.0, "L_lower": 82.3, "L_fwd": -14.9, "L_elbow": 103.0, "L_roll": -52.4,
                  "L_wpitch": 2.0, "L_thumb": 14.0}),
        (0.250, {"sp_pitch": 9.0, "sp_yaw": 4.0, "head_yaw": 0.0, "coat_trail": 3.0, "hair_lag": 3.0,
                  "R_lower": -7.1, "R_fwd": 98.5, "R_elbow": 11.5, "R_roll": -0.9, "R_wpitch": -5.5, "R_wyaw": -20.9,
                  "R_curl": 3.0, "R_fan": -8.0, "R_thumb": 26.0, "L_lower": 82.3, "L_fwd": -14.9, "L_elbow": 103.0,
                  "L_roll": -52.4, "L_wpitch": 2.0, "L_thumb": 14.0}),
        (0.400, {"pel_yaw": -19.0, "sp_pitch": 8.0, "sp_yaw": -14.0, "head_yaw": 8.0, "coat_trail": 2.0,
                  "hair_lag": 3.0, "R_lower": -1.1, "R_fwd": 80.5, "R_elbow": 9.5, "R_roll": 2.3, "R_wpitch": -8.6,
                  "R_wyaw": -24.0, "R_curl": 3.0, "R_fan": -8.0, "R_thumb": 26.0, "L_lower": 82.3, "L_fwd": -14.9,
                  "L_elbow": 103.0, "L_roll": -52.4, "L_wpitch": 2.0, "L_thumb": 14.0}),
        (0.460, {"pel_yaw": -18.0, "sp_pitch": 8.0, "sp_yaw": -11.0, "R_lower": 7.1, "R_fwd": 74.0, "R_elbow": 11.5,
                  "R_roll": 9.5, "R_wpitch": -19.6, "R_wyaw": -23.3, "R_curl": 12.0, "R_thumb": 16.0, "L_lower": 82.3,
                  "L_fwd": -14.9, "L_elbow": 103.0, "L_roll": -52.4, "L_wpitch": 2.0, "L_thumb": 14.0}),
        (F(18), {}),
    ]),
    "Cast_Tornado": (F(33), [
        (0.000, {}),
        (0.060, {"pel_z": -0.1, "sp_pitch": 9.0, "sp_yaw": 5.0, "head_pitch": 4.0, "coat_flare": 5.0,
                  "R_lower": 16.4, "R_fwd": 64.3, "R_elbow": 54.1, "R_roll": 41.2, "R_wpitch": -4.8, "R_wyaw": -20.4,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.107, {"pel_z": -0.098, "sp_pitch": 8.5, "sp_yaw": 6.5, "head_pitch": 3.2, "coat_flare": 5.4,
                  "R_lower": 10.6, "R_fwd": 76.7, "R_elbow": 34.5, "R_roll": 67.2, "R_wpitch": -2.0, "R_wyaw": -23.8,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.155, {"pel_z": -0.095, "sp_pitch": 8.0, "sp_yaw": 10.0, "head_pitch": 2.5, "coat_flare": 5.8,
                  "R_lower": 7.7, "R_fwd": 81.5, "R_elbow": 30.6, "R_roll": 83.2, "R_wpitch": -7.9, "R_wyaw": -24.6,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.203, {"pel_z": -0.092, "sp_pitch": 7.5, "sp_yaw": 13.5, "head_pitch": 1.8, "coat_flare": 6.1,
                  "R_lower": 6.3, "R_fwd": 75.0, "R_elbow": 49.6, "R_roll": 86.5, "R_wpitch": -20.3, "R_wyaw": -25.0,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.250, {"pel_z": -0.09, "sp_yaw": 15.0, "head_pitch": 1.0, "coat_flare": 6.5, "R_lower": 5.5, "R_fwd": 66.2,
                  "R_elbow": 72.9, "R_roll": 88.0, "R_wpitch": -35.2, "R_wyaw": -25.2, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0}),
        (0.297, {"pel_z": -0.088, "sp_pitch": 6.5, "sp_yaw": 13.5, "head_pitch": 0.2, "coat_flare": 6.9,
                  "R_lower": 3.6, "R_fwd": 57.3, "R_elbow": 91.0, "R_roll": 89.2, "R_wpitch": -46.8, "R_wyaw": -25.4,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.345, {"sp_pitch": 6.0, "sp_yaw": 10.0, "head_pitch": -0.5, "coat_flare": 7.2, "R_lower": -1.0,
                  "R_fwd": 49.9, "R_elbow": 97.2, "R_roll": 90.2, "R_wpitch": -49.5, "R_wyaw": -25.8, "R_curl": 82.0,
                  "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.393, {"pel_z": -0.083, "sp_pitch": 5.5, "sp_yaw": 6.5, "head_pitch": -1.2, "coat_flare": 7.6,
                  "R_lower": -6.6, "R_fwd": 49.7, "R_elbow": 87.9, "R_roll": 90.9, "R_wpitch": -43.3, "R_wyaw": -26.3,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.440, {"pel_z": -0.08, "sp_pitch": 5.0, "sp_yaw": 5.0, "head_pitch": -2.0, "coat_flare": 8.0,
                  "R_lower": -9.9, "R_fwd": 58.9, "R_elbow": 67.1, "R_roll": 90.9, "R_wpitch": -33.9, "R_wyaw": -26.8,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.620, {"pel_z": -0.06, "sp_pitch": -4.0, "sp_yaw": 8.0, "head_pitch": -12.0, "coat_flare": 9.0,
                  "hair_lag": -3.0, "R_lower": -43.4, "R_fwd": 74.3, "R_elbow": 34.2, "R_roll": 81.9,
                  "R_wpitch": -32.9, "R_wyaw": 7.8, "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (0.740, {"pel_z": -0.065, "sp_pitch": -3.0, "sp_yaw": 8.0, "head_pitch": -10.0, "coat_flare": 7.0,
                  "R_lower": -43.9, "R_fwd": 65.7, "R_elbow": 45.3, "R_roll": 80.7, "R_wpitch": -37.9, "R_wyaw": 14.0,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0}),
        (F(33), {}),
    ]),
    "Cast_WindBurst": (F(18), [
        (0.000, {}),
        (0.100, {"pel_z": -0.12, "sp_pitch": 13.0, "sp_yaw": 8.0, "head_pitch": 6.0, "coat_flare": 2.0,
                  "R_lower": 35.7, "R_fwd": 47.2, "R_elbow": 99.9, "R_clav": 5.0, "R_curl": 96.0, "R_fan": -4.0,
                  "R_thumb": 62.0, "L_lower": 53.9, "L_fwd": 24.9, "L_elbow": 116.7, "L_clav": 5.0, "L_curl": 96.0,
                  "L_fan": -4.0, "L_thumb": 62.0}),
        (0.280, {"pel_z": -0.07, "sp_pitch": -8.0, "sp_yaw": 6.0, "head_pitch": -8.0, "coat_flare": 14.0,
                  "hair_lag": -6.0, "R_lower": 12.9, "R_fwd": 54.9, "R_elbow": 11.8, "R_roll": -21.8,
                  "R_wpitch": -43.4, "R_clav": 5.0, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0, "L_lower": 14.8,
                  "L_fwd": 7.9, "L_elbow": 58.7, "L_roll": -34.8, "L_wpitch": -22.1, "L_clav": 5.0, "L_curl": 3.0,
                  "L_fan": 20.0}),
        (0.380, {"pel_z": -0.075, "sp_pitch": -6.0, "sp_yaw": 6.0, "head_pitch": -6.0, "coat_flare": 10.0,
                  "hair_lag": -3.0, "R_lower": 16.0, "R_fwd": 53.5, "R_elbow": 11.9, "R_roll": -37.6,
                  "R_wpitch": -57.2, "R_clav": 5.0, "R_fan": 14.0, "R_thumb": 12.0, "L_lower": 20.1, "L_fwd": 4.2,
                  "L_elbow": 60.4, "L_roll": -60.8, "L_wpitch": -33.7, "L_clav": 5.0, "L_curl": 10.0, "L_fan": 14.0}),
        (F(18), {"R_clav": 5.0, "L_clav": 5.0}),
    ]),
    "StoneCannon_Charge": (F(11), [
        (0.000, {}),
        (0.140, {"pel_z": -0.1, "pel_yaw": -16.0, "sp_pitch": 6.0, "sp_yaw": 12.0, "coat_flare": 5.0, "R_lower": 1.3,
                  "R_fwd": 31.1, "R_elbow": 92.2, "R_roll": 12.7, "R_wpitch": -45.6, "R_fan": 18.0, "R_thumb": 12.0,
                  "L_lower": 34.4, "L_fwd": 66.2, "L_elbow": 99.6, "L_roll": 58.5, "L_wpitch": -42.1, "L_curl": 24.0,
                  "L_thumb": 16.0}),
        (0.300, SC_HOLD),
        (F(11), SC_HOLD),
    ]),
    "StoneCannon_Release": (F(21), [
        (0.000, SC_HOLD),
        (0.100, {"pel_y": -0.015, "pel_z": -0.12, "pel_yaw": -8.0, "sp_pitch": 13.0, "sp_yaw": 2.0,
                  "head_pitch": 1.0, "coat_trail": 6.0, "hair_lag": 4.0, "R_lower": -26.4, "R_fwd": 93.8,
                  "R_elbow": 10.6, "R_roll": -10.8, "R_wpitch": -70.0, "R_wyaw": -14.6, "R_curl": 3.0, "R_fan": 20.0,
                  "R_thumb": 12.0, "L_lower": 6.6, "L_fwd": 106.3, "L_elbow": 70.5, "L_roll": 90.9, "L_wpitch": -60.4,
                  "L_curl": 58.0, "L_thumb": 40.0}),
        (0.140, {"pel_y": -0.016, "pel_z": -0.12, "pel_yaw": -8.0, "sp_pitch": 13.0, "sp_yaw": 2.0,
                  "coat_trail": 6.0, "hair_lag": 4.0, "R_lower": -27.5, "R_fwd": 94.5, "R_elbow": 9.7,
                  "R_roll": -14.6, "R_wpitch": -70.0, "R_wyaw": -14.5, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0,
                  "L_lower": 6.6, "L_fwd": 106.3, "L_elbow": 70.5, "L_roll": 90.9, "L_wpitch": -60.4, "L_curl": 58.0,
                  "L_thumb": 40.0}),
        (0.290, {"pel_y": 0.035, "pel_z": -0.11, "sp_pitch": -6.0, "sp_yaw": 8.0, "head_pitch": -8.0,
                  "coat_trail": -4.0, "hair_lag": -4.0, "R_lower": -24.7, "R_fwd": 82.8, "R_elbow": 10.7,
                  "R_roll": -9.8, "R_wpitch": -70.0, "R_wyaw": -15.7, "R_curl": 18.0, "R_fan": 14.0, "R_thumb": 14.0,
                  "L_lower": 42.8, "L_fwd": 46.1, "L_elbow": 99.0, "L_roll": 84.3, "L_wpitch": -58.4, "L_thumb": 16.0}),
        (0.450, {"pel_y": 0.01, "pel_z": -0.1, "pel_yaw": -15.0, "sp_pitch": 4.0, "head_pitch": -3.0, "R_lower": 1.8,
                  "R_fwd": 43.3, "R_elbow": 74.9, "R_roll": -9.8, "R_wpitch": -60.0, "R_wyaw": -15.7, "R_curl": 18.0,
                  "R_fan": 4.0, "R_thumb": 12.0, "L_lower": 42.8, "L_fwd": 46.1, "L_elbow": 99.0, "L_roll": 84.3,
                  "L_wpitch": -58.4, "L_thumb": 16.0}),
        (F(21), {}),
    ]),
    "Quagmire": (F(14), [
        (0.000, {}),
        (0.200, {"pel_z": -0.18, "pel_yaw": -13.0, "sp_pitch": 22.0, "sp_yaw": 6.0, "head_pitch": -8.0,
                  "coat_flare": 6.0, "R_lower": 26.9, "R_fwd": -20.3, "R_elbow": 118.4, "R_roll": -12.1,
                  "R_wpitch": -15.7, "R_curl": 24.0, "R_fan": 4.0, "R_thumb": 14.0, "L_lower": 28.5, "L_fwd": 69.7,
                  "L_elbow": 12.6, "L_roll": -0.7, "L_wpitch": -44.7, "L_wyaw": 2.2, "L_curl": 10.0, "L_fan": 14.0}),
        (0.400, QG_HOLD),
        (F(14), QG_HOLD),
    ]),
    "Quagmire_Release": (F(18), [
        (0.000, QG_HOLD),
        (0.070, {"pel_z": -0.28, "pel_yaw": -12.0, "sp_pitch": 36.0, "sp_yaw": 4.0, "head_pitch": -12.0,
                  "coat_flare": 11.0, "hair_lag": 4.0, "R_lower": 8.2, "R_fwd": -51.2, "R_elbow": 126.5,
                  "R_roll": -2.8, "R_wpitch": -26.6, "R_curl": 26.0, "R_fan": 6.0, "R_thumb": 14.0, "L_lower": 25.0,
                  "L_fwd": 75.5, "L_elbow": 7.1, "L_roll": 4.9, "L_wpitch": -63.9, "L_wyaw": 3.7, "L_curl": -2.0,
                  "L_fan": 26.0, "L_thumb": 8.0}),
        (0.200, {"pel_z": -0.27, "pel_yaw": -12.0, "sp_pitch": 35.0, "sp_yaw": 4.0, "head_pitch": -10.0,
                  "coat_flare": 9.0, "R_lower": 8.2, "R_fwd": -51.2, "R_elbow": 126.5, "R_roll": -2.8,
                  "R_wpitch": -26.6, "R_curl": 26.0, "R_fan": 6.0, "R_thumb": 14.0, "L_lower": 25.7, "L_fwd": 75.6,
                  "L_elbow": 6.9, "L_roll": 6.0, "L_wpitch": -64.0, "L_wyaw": 4.8, "L_curl": 4.0, "L_fan": 20.0,
                  "L_thumb": 10.0}),
        (F(18), {}),
    ]),
    "Barrage": (F(138), [
        (0.000, {}),
        (0.260, {"pel_z": -0.08, "sp_pitch": -3.0, "sp_yaw": 6.0, "head_pitch": -6.0, "coat_flare": 6.0,
                  "hair_lag": -2.0, "R_lower": -40.4, "R_fwd": -36.8, "R_elbow": 95.8, "R_roll": -33.2,
                  "R_wpitch": -9.0, "R_wyaw": -18.4, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0, "L_lower": -40.2,
                  "L_fwd": -61.6, "L_elbow": 97.1, "L_roll": -40.6, "L_wpitch": 2.5, "L_wyaw": -15.8, "L_curl": 3.0,
                  "L_fan": 20.0}),
        (0.440, {"pel_z": -0.12, "sp_pitch": 5.0, "sp_yaw": 6.0, "head_pitch": 2.0, "coat_flare": 8.0,
                  "hair_lag": 2.0, "R_lower": 48.6, "R_fwd": -13.8, "R_elbow": 52.0, "R_roll": -34.5,
                  "R_wpitch": -31.3, "R_wyaw": -19.8, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0, "L_lower": 52.0,
                  "L_fwd": -37.5, "L_elbow": 49.4, "L_roll": -38.2, "L_wpitch": -28.6, "L_wyaw": -16.0, "L_curl": 3.0,
                  "L_fan": 20.0}),
        (0.600, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": 10.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -9.9, "R_fwd": 62.6, "R_elbow": 60.7, "R_roll": 9.1, "R_wpitch": -26.7, "R_wyaw": -19.7,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 21.2, "L_fwd": 37.1,
                  "L_elbow": 79.4, "L_roll": -38.2, "L_wpitch": -28.6, "L_wyaw": -16.0, "L_curl": 3.0, "L_fan": 20.0}),
        (0.700, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": 6.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -30.2, "R_fwd": 52.0, "R_elbow": 68.9, "R_roll": 9.1, "R_wpitch": -26.7, "R_wyaw": -18.3,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 25.8, "L_fwd": 23.9,
                  "L_elbow": 109.9, "L_roll": -47.9, "L_wpitch": -38.9, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (0.800, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": -2.0, "coat_flare": 6.0, "R_lower": -12.8, "R_fwd": 101.7,
                  "R_elbow": 11.6, "R_roll": 9.1, "R_wpitch": -26.7, "R_wyaw": -18.1, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 31.5, "L_fwd": 10.6, "L_elbow": 115.9, "L_roll": -54.7,
                  "L_wpitch": -43.0, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0, "L_thumb": 16.0}),
        (0.900, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 0.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": 4.2, "R_fwd": 71.3, "R_elbow": 44.4, "R_roll": 9.1, "R_wpitch": -26.7, "R_wyaw": -18.1,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 26.5, "L_fwd": 14.1,
                  "L_elbow": 115.7, "L_roll": -59.1, "L_wpitch": -44.8, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (1.000, {"pel_z": -0.115, "sp_pitch": 8.0, "sp_yaw": -2.0, "head_pitch": -1.0, "coat_flare": 6.0,
                  "R_lower": -4.8, "R_fwd": 101.6, "R_elbow": 11.2, "R_roll": 9.1, "R_wpitch": -26.7, "R_wyaw": -18.0,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 25.9, "L_fwd": 10.9,
                  "L_elbow": 117.7, "L_roll": -62.1, "L_wpitch": -45.3, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (1.100, {"pel_z": -0.105, "sp_pitch": 8.0, "sp_yaw": 4.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -10.1, "R_fwd": 73.1, "R_elbow": 51.8, "R_roll": 35.2, "R_wpitch": -23.6,
                  "R_wyaw": -16.5, "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": -28.1,
                  "L_fwd": 5.0, "L_elbow": 110.1, "L_roll": -62.1, "L_wpitch": -45.3, "L_wyaw": -16.0, "L_curl": 24.0,
                  "L_fan": 4.0, "L_thumb": 16.0}),
        (1.200, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": 12.0, "coat_flare": 6.0, "R_lower": -10.7, "R_fwd": 59.5,
                  "R_elbow": 62.6, "R_roll": 50.0, "R_wpitch": -26.5, "R_wyaw": -14.9, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": -2.7, "L_fwd": 61.2, "L_elbow": 65.5, "L_roll": -62.1,
                  "L_wpitch": -45.3, "L_wyaw": -16.0, "L_curl": 3.0, "L_fan": 20.0}),
        (1.300, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 14.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -12.7, "R_fwd": 55.9, "R_elbow": 65.4, "R_roll": 59.4, "R_wpitch": -28.4,
                  "R_wyaw": -12.9, "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 23.4,
                  "L_fwd": 27.9, "L_elbow": 88.1, "L_roll": -62.1, "L_wpitch": -45.3, "L_wyaw": -16.0, "L_curl": 24.0,
                  "L_fan": 4.0, "L_thumb": 16.0}),
        (1.400, {"pel_z": -0.115, "sp_pitch": 8.0, "sp_yaw": 12.0, "head_pitch": -1.0, "coat_flare": 6.0,
                  "R_lower": -13.4, "R_fwd": 59.1, "R_elbow": 63.0, "R_roll": 65.2, "R_wpitch": -28.2,
                  "R_wyaw": -10.6, "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 5.1,
                  "L_fwd": 63.6, "L_elbow": 60.6, "L_roll": -62.1, "L_wpitch": -45.3, "L_wyaw": -16.0, "L_curl": 3.0,
                  "L_fan": 20.0}),
        (1.500, {"pel_z": -0.105, "sp_pitch": 8.0, "sp_yaw": 11.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -33.2, "R_fwd": 43.1, "R_elbow": 73.9, "R_roll": 65.2, "R_wpitch": -28.2,
                  "R_wyaw": -10.6, "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 21.7,
                  "L_fwd": 31.8, "L_elbow": 106.4, "L_roll": -64.1, "L_wpitch": -47.8, "L_wyaw": -16.0,
                  "L_curl": 22.0, "L_fan": 8.0, "L_thumb": 16.0}),
        (1.600, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": -2.0, "coat_flare": 6.0, "R_lower": -12.8, "R_fwd": 101.6,
                  "R_elbow": 11.7, "R_roll": 65.2, "R_wpitch": -28.2, "R_wyaw": -10.6, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 31.5, "L_fwd": 10.8, "L_elbow": 115.7, "L_roll": -66.0,
                  "L_wpitch": -47.3, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0, "L_thumb": 16.0}),
        (1.700, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 0.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": 4.2, "R_fwd": 71.3, "R_elbow": 44.4, "R_roll": 65.2, "R_wpitch": -28.2, "R_wyaw": -10.6,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 26.6, "L_fwd": 14.2,
                  "L_elbow": 115.7, "L_roll": -67.1, "L_wpitch": -46.9, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (1.800, {"pel_z": -0.115, "sp_pitch": 8.0, "sp_yaw": -2.0, "head_pitch": -1.0, "coat_flare": 6.0,
                  "R_lower": -4.8, "R_fwd": 101.6, "R_elbow": 11.1, "R_roll": 65.2, "R_wpitch": -28.2,
                  "R_wyaw": -10.6, "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 26.0,
                  "L_fwd": 11.0, "L_elbow": 117.7, "L_roll": -67.7, "L_wpitch": -46.3, "L_wyaw": -16.0,
                  "L_curl": 22.0, "L_fan": 8.0, "L_thumb": 16.0}),
        (1.900, {"pel_z": -0.105, "sp_pitch": 8.0, "sp_yaw": 4.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -10.3, "R_fwd": 73.0, "R_elbow": 51.5, "R_roll": 67.5, "R_wpitch": -24.7, "R_wyaw": -6.9,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": -28.1, "L_fwd": 5.0,
                  "L_elbow": 110.1, "L_roll": -67.7, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 24.0, "L_fan": 4.0,
                  "L_thumb": 16.0}),
        (2.000, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": 12.0, "coat_flare": 6.0, "R_lower": -10.8, "R_fwd": 59.5,
                  "R_elbow": 62.5, "R_roll": 69.6, "R_wpitch": -27.4, "R_wyaw": -5.7, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": -2.7, "L_fwd": 61.2, "L_elbow": 65.5, "L_roll": -67.7,
                  "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 3.0, "L_fan": 20.0}),
        (2.100, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 14.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -12.8, "R_fwd": 55.8, "R_elbow": 65.3, "R_roll": 71.8, "R_wpitch": -29.0, "R_wyaw": -5.6,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 23.4, "L_fwd": 27.9,
                  "L_elbow": 88.1, "L_roll": -67.7, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 24.0, "L_fan": 4.0,
                  "L_thumb": 16.0}),
        (2.200, {"pel_z": -0.115, "sp_pitch": 8.0, "sp_yaw": 12.0, "head_pitch": -1.0, "coat_flare": 6.0,
                  "R_lower": -13.5, "R_fwd": 59.0, "R_elbow": 63.0, "R_roll": 73.2, "R_wpitch": -28.6, "R_wyaw": -5.4,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 5.1, "L_fwd": 63.6,
                  "L_elbow": 60.6, "L_roll": -67.7, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 3.0, "L_fan": 20.0}),
        (2.300, {"pel_z": -0.105, "sp_pitch": 8.0, "sp_yaw": 11.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -33.2, "R_fwd": 43.1, "R_elbow": 73.9, "R_roll": 73.2, "R_wpitch": -28.6, "R_wyaw": -5.4,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 21.7, "L_fwd": 31.8,
                  "L_elbow": 106.4, "L_roll": -68.2, "L_wpitch": -48.3, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (2.400, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": -2.0, "coat_flare": 6.0, "R_lower": -12.8, "R_fwd": 101.6,
                  "R_elbow": 11.7, "R_roll": 73.2, "R_wpitch": -28.6, "R_wyaw": -5.4, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 31.5, "L_fwd": 10.9, "L_elbow": 115.7, "L_roll": -69.0,
                  "L_wpitch": -47.5, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0, "L_thumb": 16.0}),
        (2.500, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 0.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": 4.2, "R_fwd": 71.3, "R_elbow": 44.4, "R_roll": 73.2, "R_wpitch": -28.6, "R_wyaw": -5.4,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 26.6, "L_fwd": 14.2,
                  "L_elbow": 115.7, "L_roll": -69.3, "L_wpitch": -47.0, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (2.600, {"pel_z": -0.115, "sp_pitch": 8.0, "sp_yaw": -2.0, "head_pitch": -1.0, "coat_flare": 6.0,
                  "R_lower": -4.8, "R_fwd": 101.6, "R_elbow": 11.1, "R_roll": 73.2, "R_wpitch": -28.6, "R_wyaw": -5.4,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 26.0, "L_fwd": 11.0,
                  "L_elbow": 117.7, "L_roll": -69.3, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (2.700, {"pel_z": -0.105, "sp_pitch": 8.0, "sp_yaw": 4.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -10.3, "R_fwd": 73.0, "R_elbow": 51.5, "R_roll": 72.5, "R_wpitch": -24.9, "R_wyaw": -3.6,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": -28.1, "L_fwd": 5.0,
                  "L_elbow": 110.1, "L_roll": -69.3, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 24.0, "L_fan": 4.0,
                  "L_thumb": 16.0}),
        (2.800, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": 12.0, "coat_flare": 6.0, "R_lower": -10.8, "R_fwd": 59.5,
                  "R_elbow": 62.4, "R_roll": 72.9, "R_wpitch": -27.5, "R_wyaw": -3.4, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": -2.7, "L_fwd": 61.2, "L_elbow": 65.5, "L_roll": -69.3,
                  "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 3.0, "L_fan": 20.0}),
        (2.900, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 14.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -12.8, "R_fwd": 55.8, "R_elbow": 65.3, "R_roll": 74.0, "R_wpitch": -29.1, "R_wyaw": -4.0,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 23.4, "L_fwd": 27.9,
                  "L_elbow": 88.1, "L_roll": -69.3, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 24.0, "L_fan": 4.0,
                  "L_thumb": 16.0}),
        (3.000, {"pel_z": -0.115, "sp_pitch": 8.0, "sp_yaw": 12.0, "head_pitch": -1.0, "coat_flare": 6.0,
                  "R_lower": -13.5, "R_fwd": 59.0, "R_elbow": 63.0, "R_roll": 74.7, "R_wpitch": -28.7, "R_wyaw": -4.3,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 5.1, "L_fwd": 63.6,
                  "L_elbow": 60.6, "L_roll": -69.3, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 3.0, "L_fan": 20.0}),
        (3.100, {"pel_z": -0.105, "sp_pitch": 8.0, "sp_yaw": 11.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -33.2, "R_fwd": 43.1, "R_elbow": 73.9, "R_roll": 74.7, "R_wpitch": -28.7, "R_wyaw": -4.3,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 21.7, "L_fwd": 31.8,
                  "L_elbow": 106.4, "L_roll": -69.4, "L_wpitch": -48.3, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (3.200, {"pel_z": -0.1, "sp_pitch": 8.0, "sp_yaw": -2.0, "coat_flare": 6.0, "R_lower": -12.8, "R_fwd": 101.6,
                  "R_elbow": 11.7, "R_roll": 74.7, "R_wpitch": -28.7, "R_wyaw": -4.3, "R_curl": 82.0, "R_fan": -2.0,
                  "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 31.5, "L_fwd": 10.9, "L_elbow": 115.7, "L_roll": -69.8,
                  "L_wpitch": -47.5, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0, "L_thumb": 16.0}),
        (3.300, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 0.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": 4.2, "R_fwd": 71.3, "R_elbow": 44.4, "R_roll": 74.7, "R_wpitch": -28.7, "R_wyaw": -4.3,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 26.6, "L_fwd": 14.2,
                  "L_elbow": 115.7, "L_roll": -69.8, "L_wpitch": -47.0, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (3.400, {"pel_z": -0.115, "sp_pitch": 8.0, "sp_yaw": -2.0, "head_pitch": -1.0, "coat_flare": 6.0,
                  "R_lower": -4.8, "R_fwd": 101.6, "R_elbow": 11.1, "R_roll": 74.7, "R_wpitch": -28.7, "R_wyaw": -4.3,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 26.0, "L_fwd": 11.0,
                  "L_elbow": 117.7, "L_roll": -69.6, "L_wpitch": -46.3, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (3.550, {"pel_z": -0.11, "sp_pitch": 8.0, "sp_yaw": 6.0, "head_pitch": -2.0, "coat_flare": 6.0,
                  "R_lower": -11.5, "R_fwd": 69.6, "R_elbow": 54.4, "R_roll": 74.0, "R_wpitch": -25.8, "R_wyaw": -3.4,
                  "R_curl": 82.0, "R_fan": -2.0, "R_thumb": 48.0, "R_ci": -84.0, "L_lower": 23.0, "L_fwd": 23.8,
                  "L_elbow": 111.2, "L_roll": -69.6, "L_wpitch": -47.2, "L_wyaw": -16.0, "L_curl": 22.0, "L_fan": 8.0,
                  "L_thumb": 16.0}),
        (3.700, {"pel_z": -0.12, "pel_yaw": -13.0, "sp_pitch": 6.0, "sp_yaw": 6.0, "head_pitch": 0.0,
                  "coat_flare": 7.0, "R_lower": 2.5, "R_fwd": 12.4, "R_elbow": 91.4, "R_roll": 77.2,
                  "R_wpitch": -22.9, "R_wyaw": 8.8, "R_curl": 3.0, "R_fan": 20.0, "R_thumb": 12.0, "L_lower": 9.7,
                  "L_fwd": -11.1, "L_elbow": 98.4, "L_roll": -31.4, "L_wpitch": -49.1, "L_wyaw": -18.8, "L_curl": 3.0,
                  "L_fan": 20.0}),
        (3.870, {"pel_z": -0.15, "pel_yaw": -12.0, "sp_pitch": 12.0, "sp_yaw": 4.0, "head_pitch": 4.0,
                  "coat_flare": 8.0, "R_lower": -9.6, "R_fwd": 71.3, "R_elbow": 82.4, "R_roll": 34.1,
                  "R_wpitch": -69.6, "R_wyaw": 17.5, "R_curl": 36.0, "R_fan": 4.0, "R_thumb": 24.0, "L_lower": -8.6,
                  "L_fwd": 45.5, "L_elbow": 99.6, "L_roll": -33.4, "L_wpitch": -70.0, "L_wyaw": -21.8, "L_curl": 36.0,
                  "L_fan": 4.0, "L_thumb": 24.0}),
        (3.950, {"pel_y": -0.03, "pel_z": -0.14, "pel_yaw": -8.0, "sp_pitch": 14.0, "sp_yaw": 2.0, "head_pitch": 2.0,
                  "coat_trail": 8.0, "coat_flare": 9.0, "hair_lag": 5.0, "R_lower": -15.1, "R_fwd": 98.0,
                  "R_elbow": 12.8, "R_roll": 15.4, "R_wpitch": -70.0, "R_wyaw": 13.8, "R_curl": 3.0, "R_fan": 20.0,
                  "R_thumb": 12.0, "L_lower": -17.1, "L_fwd": 68.0, "L_elbow": 43.5, "L_roll": -32.2,
                  "L_wpitch": -70.0, "L_wyaw": -23.5, "L_curl": 3.0, "L_fan": 20.0}),
        (4.030, {"pel_y": -0.032, "pel_z": -0.14, "pel_yaw": -8.0, "sp_pitch": 14.0, "sp_yaw": 2.0,
                  "head_pitch": 2.0, "coat_trail": 7.0, "coat_flare": 8.0, "hair_lag": 5.0, "R_lower": -16.4,
                  "R_fwd": 98.9, "R_elbow": 11.3, "R_roll": 6.9, "R_wpitch": -70.0, "R_wyaw": 11.3, "R_curl": 3.0,
                  "R_fan": 20.0, "R_thumb": 12.0, "L_lower": -18.2, "L_fwd": 71.2, "L_elbow": 36.8, "L_roll": -31.9,
                  "L_wpitch": -70.0, "L_wyaw": -23.5, "L_curl": 3.0, "L_fan": 20.0}),
        (4.180, {"pel_y": 0.03, "pel_z": -0.12, "pel_yaw": -12.0, "sp_pitch": -6.0, "sp_yaw": 6.0,
                  "head_pitch": -8.0, "coat_trail": -4.0, "coat_flare": 6.0, "hair_lag": -4.0, "R_lower": -18.5,
                  "R_fwd": 91.0, "R_elbow": 10.3, "R_roll": 13.5, "R_wpitch": -70.0, "R_wyaw": 11.0, "R_curl": 16.0,
                  "R_fan": 12.0, "R_thumb": 12.0, "L_lower": -20.3, "L_fwd": 74.8, "L_elbow": 19.6, "L_roll": -25.8,
                  "L_wpitch": -70.0, "L_wyaw": -21.7, "L_curl": 16.0, "L_fan": 12.0}),
        (4.360, {"pel_y": 0.01, "pel_z": -0.1, "sp_pitch": 4.0, "sp_yaw": 8.0, "head_pitch": -3.0, "R_lower": 16.7,
                  "R_fwd": 49.0, "R_elbow": 67.9, "R_roll": 13.5, "R_wpitch": -60.0, "R_wyaw": 10.2, "R_curl": 16.0,
                  "R_fan": 4.0, "R_thumb": 12.0, "L_lower": 43.2, "L_fwd": 19.4, "L_elbow": 94.9, "L_roll": -25.8,
                  "L_wpitch": -60.0, "L_wyaw": -18.6, "L_curl": 26.0, "L_fan": 2.0}),
        (F(138), {}),
    ]),
}

R_EVENTS = {
    "Cast_Fireball": {"Release": 0.30}, "Cast_Fireball_Release": {"Release": 0.04},
    "Cast_FlameWave": {"Release": 0.42}, "Cast_Inferno": {"Release": 0.90},
    "Cast_WaterBullet": {"Release": 0.22}, "Cast_WaterDragon": {"Release": 0.75}, "Cast_Flood": {"Release": 0.70},
    "Cast_StoneCannon": {"Release": 0.35}, "Cast_StoneCannon_Release": {"Release": 0.04},
    "Cast_EarthWall": {"Release": 0.40}, "Cast_EarthSpikes": {"Release": 0.40},
    "Cast_WindBlade": {"Release": 0.25}, "Cast_Tornado": {"Release": 0.55}, "Cast_WindBurst": {"Release": 0.12},
    "StoneCannon_Charge": {"Release": 0.35}, "StoneCannon_Release": {"Release": 0.04},
    "Quagmire": {"Release": 0.45}, "Quagmire_Release": {"Release": 0.04},
    "Barrage": {"Release": 0.60, "Finale": 3.95},
}


def fireball_hold(P0, period):
    """The fingers roll the sphere inward (a wave from the index to the little finger), the palm turns under it and the
    left hand circles over it."""
    def fn(t):
        w = TAU * (t % period) / period
        P = dict(P0)
        for i, k in enumerate(("R_ci", "R_cm", "R_cr", "R_cp")):
            P[k] = P0.get(k, 0.0) + 8.0 * _wave(w, -0.9 * i)
        for i, k in enumerate(("L_ci", "L_cm", "L_cr", "L_cp")):
            P[k] = P0.get(k, 0.0) + 5.0 * _wave(w, 0.9 * i + 1.0)
        P["R_roll"] = P0.get("R_roll", 0.0) + 5.0 * math.sin(w)
        P["R_wyaw"] = P0.get("R_wyaw", 0.0) + 3.0 * math.sin(2.0 * w)
        P["L_fwd"] = P0["L_fwd"] + 3.0 * (math.cos(w) - 1.0)
        P["L_lower"] = P0["L_lower"] + 2.5 * math.sin(w)
        P["L_roll"] = P0.get("L_roll", 0.0) - 4.0 * math.sin(w)
        P["sp_pitch"] = P0["sp_pitch"] + 0.8 * math.sin(w)
        P["pel_z"] = P0["pel_z"] + 0.004 * math.sin(2.0 * w)
        P["hair_lag"] = P0.get("hair_lag", 0.0) + 0.8 * math.sin(2.0 * w)
        P["coat_flare"] = P0.get("coat_flare", 0.0) + 0.8 * math.sin(w)
        return P
    return fn


def stone_hold(P0, period, tremor=1.2, press=5.0):
    """Compression: the fingers tighten in pulses, the hand trembles with the spinning slug (4-5 Hz, small), the wrist
    turns the core. The left hand's grip pulses with it when it braces the forearm."""
    def fn(t):
        w = TAU * (t % period) / period
        P = dict(P0)
        P["R_curl"] = P0["R_curl"] + press * math.sin(2.0 * w)
        P["R_elbow"] = P0["R_elbow"] + tremor * math.sin(10.0 * w)
        P["R_wpitch"] = P0.get("R_wpitch", 0.0) + 0.6 * tremor * math.sin(10.0 * w + 1.3)
        P["R_roll"] = P0.get("R_roll", 0.0) + 4.0 * math.sin(w)
        P["L_curl"] = P0.get("L_curl", 0.0) + 0.6 * press * math.sin(2.0 * w)
        P["sp_pitch"] = P0["sp_pitch"] + 0.7 * math.sin(w)
        P["pel_z"] = P0["pel_z"] + 0.003 * math.sin(2.0 * w)
        P["hair_lag"] = P0.get("hair_lag", 0.0) + 0.6 * math.sin(2.0 * w)
        return P
    return fn


def quagmire_hold(P0, period):
    """Pressing: the left palm pushes down twice a second, the fingers flex against the mud, the body presses with it."""
    def fn(t):
        w = TAU * (t % period) / period
        P = dict(P0)
        P["L_lower"] = P0["L_lower"] + 2.5 * math.sin(2.0 * w)
        P["L_elbow"] = P0["L_elbow"] - 2.0 * math.sin(2.0 * w)
        P["L_curl"] = P0["L_curl"] + 5.0 * (1.0 - math.cos(2.0 * w)) * 0.5
        P["L_fan"] = P0.get("L_fan", 0.0) - 3.0 * (1.0 - math.cos(2.0 * w)) * 0.5
        P["sp_pitch"] = P0["sp_pitch"] + 1.0 * math.sin(2.0 * w)
        P["pel_z"] = P0["pel_z"] - 0.006 * math.sin(2.0 * w)
        P["coat_flare"] = P0.get("coat_flare", 0.0) + 1.0 * math.sin(w)
        P["hair_lag"] = P0.get("hair_lag", 0.0) + 0.8 * math.sin(2.0 * w)
        return P
    return fn


# ============================================================================================================ Orsted
# Every delta below is applied on top of clips_orsted.GUARD.
# Fireball held: right palm turned up at the waist, fingers barely closed
OFB_HOLD = {"sp_pitch": 3.0, "head_pitch": 3.0, "R_lower": 50.7, "R_fwd": 43.4, "R_elbow": 64.7, "R_roll": 80.9,
            "R_wpitch": 5.1, "R_wyaw": 14.3, "R_curl": 32.0, "R_fan": 6.0, "R_thumb": 20.0}
# Stone Cannon held: right hand forward at the chest, fingers closed a little
OSC_HOLD = {"sp_yaw": 8.0, "R_lower": 23.8, "R_fwd": 60.8, "R_elbow": 51.5, "R_roll": -9.2, "R_wpitch": -70.0,
            "R_wyaw": 10.0, "R_curl": 42.0, "R_fan": 2.0, "R_thumb": 30.0}

O_KEYS = {
    "Cast_Fireball": (F(6), [
        (0.000, {}),
        (0.100, {"sp_pitch": 2.5, "head_pitch": 2.0, "R_lower": 54.9, "R_fwd": 38.9, "R_elbow": 58.7, "R_roll": 39.3,
                  "R_wpitch": -5.4, "R_wyaw": 13.3, "R_curl": 22.0, "R_fan": 8.0, "R_thumb": 14.0}),
        (F(6), OFB_HOLD),
    ]),
    "Cast_Fireball_Release": (F(10), [
        (0.000, OFB_HOLD),
        (0.070, {"sp_pitch": 3.5, "sp_yaw": 5.0, "head_pitch": 2.0, "coat_trail": 2.0, "R_lower": 28.0,
                  "R_fwd": 79.3, "R_elbow": 24.6, "R_roll": 95.0, "R_wpitch": 0.9, "R_wyaw": 9.2, "R_curl": 4.0,
                  "R_fan": 12.0, "R_thumb": 8.0}),
        (0.140, {"sp_pitch": 3.0, "sp_yaw": 5.5, "head_pitch": 1.5, "R_lower": 26.1, "R_fwd": 79.4, "R_elbow": 24.3,
                  "R_roll": 95.0, "R_wpitch": 7.3, "R_wyaw": 11.8, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0}),
        (F(10), {}),
    ]),
    "Cast_FlameWave": (F(18), [
        (0.000, {}),
        (0.140, {"pel_yaw": -8.0, "sp_yaw": 13.0, "head_yaw": -4.0, "R_lower": 39.9, "R_fwd": 87.8, "R_elbow": 37.8,
                  "R_roll": -17.4, "R_wpitch": -36.8, "R_wyaw": -4.1, "R_curl": 10.0, "R_fan": 8.0, "R_thumb": 10.0}),
        (0.260, {"pel_yaw": -11.0, "sp_yaw": 4.0, "head_yaw": 0.0, "coat_trail": 2.0, "R_lower": 29.0, "R_fwd": 85.6,
                  "R_elbow": 9.2, "R_roll": -9.4, "R_wpitch": -41.3, "R_wyaw": -6.0, "R_curl": 4.0, "R_fan": 12.0,
                  "R_thumb": 8.0}),
        (0.360, {"pel_yaw": -13.0, "sp_yaw": -3.0, "R_lower": 30.3, "R_fwd": 62.3, "R_elbow": 10.8, "R_roll": 5.9,
                  "R_wpitch": -51.1, "R_wyaw": -19.3, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0}),
        (F(18), {}),
    ]),
    "Cast_Inferno": (F(29), [
        (0.000, {}),
        (0.260, {"pel_z": -0.04, "sp_pitch": -1.0, "head_pitch": -6.0, "R_lower": -50.3, "R_fwd": 34.1,
                  "R_elbow": 91.3, "R_roll": -34.1, "R_wpitch": -33.6, "R_fan": 12.0, "R_thumb": 8.0}),
        (0.360, {"pel_z": -0.04, "sp_pitch": -1.5, "head_pitch": -7.0, "R_lower": -45.4, "R_fwd": 37.1,
                  "R_elbow": 90.0, "R_roll": -61.1, "R_wpitch": -42.1, "R_curl": 92.0, "R_fan": -4.0, "R_thumb": 58.0}),
        (0.550, {"pel_y": -0.02, "pel_z": -0.08, "sp_pitch": 7.0, "coat_flare": 4.0, "R_lower": 14.9, "R_fwd": 54.2,
                  "R_elbow": 80.5, "R_roll": -61.1, "R_wpitch": -42.1, "R_curl": 92.0, "R_fan": -4.0, "R_thumb": 58.0}),
        (0.700, {"pel_y": -0.018, "pel_z": -0.075, "sp_pitch": 6.0, "head_pitch": -1.0, "coat_flare": 3.0,
                  "R_lower": 15.8, "R_fwd": 52.0, "R_elbow": 82.1, "R_roll": -61.1, "R_wpitch": -42.1, "R_curl": 92.0,
                  "R_fan": -4.0, "R_thumb": 58.0}),
        (F(29), {}),
    ]),
    "Cast_WaterBullet": (F(11), [
        (0.000, {}),
        (0.080, {"sp_yaw": 9.0, "R_lower": 44.0, "R_fwd": 38.3, "R_elbow": 70.1, "R_roll": 3.0, "R_wpitch": -29.3,
                  "R_wyaw": 10.6, "R_curl": 80.0, "R_fan": -5.0, "R_thumb": 46.0, "R_ci": -82.0, "R_cm": -84.0}),
        (0.140, {"sp_yaw": 6.0, "R_lower": 28.2, "R_fwd": 64.8, "R_elbow": 43.7, "R_roll": 23.8, "R_wpitch": -28.2,
                  "R_wyaw": 5.3, "R_curl": 80.0, "R_fan": -5.0, "R_thumb": 46.0, "R_ci": -82.0, "R_cm": -84.0}),
        (0.210, {"sp_yaw": 6.5, "R_lower": 27.5, "R_fwd": 59.6, "R_elbow": 52.9, "R_roll": 30.6, "R_wpitch": -34.7,
                  "R_wyaw": 11.0, "R_curl": 80.0, "R_fan": -5.0, "R_thumb": 46.0, "R_ci": -82.0, "R_cm": -84.0}),
        (F(11), {}),
    ]),
    "Cast_WaterDragon": (F(27), [
        (0.000, {}),
        (0.080, {"sp_pitch": 2.0, "sp_yaw": 0.0, "head_pitch": 0.0, "R_lower": 50.6, "R_fwd": 59.1, "R_elbow": 62.1,
                  "R_roll": 14.7, "R_wpitch": -15.7, "R_curl": 14.0, "R_fan": 8.0, "R_thumb": 10.0, "L_lower": 66.0,
                  "L_fwd": 21.6, "L_elbow": 77.1, "L_roll": 10.8, "L_wpitch": -13.2, "L_curl": 14.0, "L_fan": 8.0,
                  "L_thumb": 10.0}),
        (0.130, {"pel_z": -0.046, "sp_pitch": 1.4, "sp_yaw": 1.9, "head_pitch": -0.8, "R_lower": 41.2, "R_fwd": 59.1,
                  "R_elbow": 58.7, "R_roll": 28.4, "R_wpitch": -17.6, "R_curl": 14.0, "R_fan": 8.0, "R_thumb": 10.0,
                  "L_lower": 50.1, "L_fwd": 31.7, "L_elbow": 73.1, "L_roll": 22.7, "L_wpitch": -16.5, "L_curl": 14.0,
                  "L_fan": 8.0, "L_thumb": 10.0}),
        (0.180, {"pel_z": -0.042, "sp_pitch": 0.8, "sp_yaw": 1.2, "head_pitch": -1.6, "R_lower": 39.7, "R_fwd": 46.3,
                  "R_elbow": 69.8, "R_roll": 38.7, "R_wpitch": -18.0, "R_curl": 14.0, "R_fan": 8.0, "R_thumb": 10.0,
                  "L_lower": 50.0, "L_fwd": 16.2, "L_elbow": 84.1, "L_roll": 31.2, "L_wpitch": -17.5, "L_curl": 14.0,
                  "L_fan": 8.0, "L_thumb": 10.0}),
        (0.230, {"pel_z": -0.038, "sp_pitch": 0.2, "sp_yaw": -1.2, "head_pitch": -2.4, "R_lower": 44.9,
                  "R_fwd": 34.5, "R_elbow": 90.0, "R_roll": 44.3, "R_wpitch": -19.3, "R_curl": 14.0, "R_fan": 8.0,
                  "R_thumb": 10.0, "L_lower": 65.5, "L_fwd": -7.1, "L_elbow": 105.2, "L_roll": 33.2,
                  "L_wpitch": -16.6, "L_curl": 14.0, "L_fan": 8.0, "L_thumb": 10.0}),
        (0.280, {"pel_z": -0.034, "sp_pitch": -0.4, "sp_yaw": -1.9, "head_pitch": -3.2, "R_lower": 44.0,
                  "R_fwd": 39.6, "R_elbow": 101.2, "R_roll": 47.8, "R_wpitch": -23.8, "R_curl": 14.0, "R_fan": 8.0,
                  "R_thumb": 10.0, "L_lower": 70.4, "L_fwd": -2.8, "L_elbow": 117.0, "L_roll": 32.4,
                  "L_wpitch": -18.4, "L_curl": 14.0, "L_fan": 8.0, "L_thumb": 10.0}),
        (0.330, {"pel_z": -0.03, "sp_pitch": -1.0, "sp_yaw": 0.0, "head_pitch": -4.0, "R_lower": 28.8, "R_fwd": 52.3,
                  "R_elbow": 94.5, "R_roll": 53.7, "R_wpitch": -29.8, "R_curl": 14.0, "R_fan": 8.0, "R_thumb": 10.0,
                  "L_lower": 38.9, "L_fwd": 24.8, "L_elbow": 109.0, "L_roll": 37.4, "L_wpitch": -27.0, "L_curl": 14.0,
                  "L_fan": 8.0, "L_thumb": 10.0}),
        (0.450, {"pel_z": -0.04, "pel_yaw": -12.0, "sp_pitch": 2.0, "sp_yaw": 6.0, "R_lower": 9.8, "R_fwd": 74.4,
                  "R_elbow": 42.8, "R_roll": 56.8, "R_wpitch": -27.1, "R_wyaw": 7.2, "R_curl": 80.0, "R_fan": -2.0,
                  "R_thumb": 44.0, "R_ci": -82.0, "L_lower": 60.4, "L_fwd": 4.5, "L_elbow": 109.1, "L_roll": 37.4,
                  "L_wpitch": -27.0, "L_curl": 12.0, "L_fan": 4.0}),
        (0.600, {"pel_z": -0.04, "pel_yaw": -12.0, "sp_pitch": 2.0, "sp_yaw": 6.0, "R_lower": 12.3, "R_fwd": 72.1,
                  "R_elbow": 44.8, "R_roll": 59.0, "R_wpitch": -25.7, "R_wyaw": 10.2, "R_curl": 80.0, "R_fan": -2.0,
                  "R_thumb": 44.0, "R_ci": -82.0, "L_lower": 82.5, "L_fwd": -20.2, "L_elbow": 72.5, "L_roll": 37.4,
                  "L_wpitch": -27.0, "L_curl": 10.0}),
        (F(27), {}),
    ]),
    "Cast_Flood": (F(27), [
        (0.000, {}),
        (0.190, {"pel_y": 0.015, "sp_pitch": -1.0, "R_lower": 88.7, "R_fwd": -29.1, "R_elbow": 56.6, "R_roll": -8.3,
                  "R_wpitch": -35.3, "R_curl": 16.0, "R_fan": 6.0, "R_thumb": 10.0, "L_lower": 88.9, "L_fwd": -37.1,
                  "L_elbow": 54.6, "L_roll": -7.7, "L_wpitch": -34.0, "L_curl": 16.0, "L_fan": 6.0, "L_thumb": 10.0}),
        (0.420, {"pel_y": -0.025, "pel_z": -0.08, "sp_pitch": 6.0, "coat_trail": 3.0, "R_lower": 32.6, "R_fwd": 83.3,
                  "R_elbow": 13.5, "R_roll": -11.3, "R_wpitch": -60.9, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0,
                  "L_lower": 34.1, "L_fwd": 75.2, "L_elbow": 22.1, "L_roll": -13.4, "L_wpitch": -60.5, "L_curl": 4.0,
                  "L_fan": 12.0}),
        (0.580, {"pel_y": -0.022, "pel_z": -0.075, "sp_pitch": 5.0, "R_lower": 34.8, "R_fwd": 84.2, "R_elbow": 11.6,
                  "R_roll": -14.2, "R_wpitch": -64.9, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0, "L_lower": 36.0,
                  "L_fwd": 80.2, "L_elbow": 13.4, "L_roll": -18.2, "L_wpitch": -64.7, "L_curl": 4.0, "L_fan": 12.0}),
        (F(27), {}),
    ]),
    "Cast_StoneCannon": (F(7), [
        (0.000, {}),
        (0.150, {"R_lower": 30.2, "R_fwd": 57.0, "R_elbow": 52.8, "R_roll": 3.0, "R_wpitch": -45.1, "R_curl": 26.0,
                  "R_fan": 6.0, "R_thumb": 16.0}),
        (F(7), OSC_HOLD),
    ]),
    "Cast_StoneCannon_Release": (F(9), [
        (0.000, OSC_HOLD),
        (0.060, {"sp_yaw": 5.0, "coat_trail": 2.0, "R_lower": 16.3, "R_fwd": 88.3, "R_elbow": 10.0, "R_roll": -0.5,
                  "R_wpitch": -70.0, "R_wyaw": 6.3, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0}),
        (0.120, {"sp_yaw": 5.0, "R_lower": 15.6, "R_fwd": 88.6, "R_elbow": 9.5, "R_roll": 4.5, "R_wpitch": -70.0,
                  "R_wyaw": 8.5, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0}),
        (F(9), {}),
    ]),
    "Cast_EarthWall": (F(16), [
        (0.000, {}),
        (0.120, {"pel_z": -0.06, "sp_pitch": 4.0, "R_lower": 51.0, "R_fwd": 55.1, "R_elbow": 28.0, "R_roll": 38.9,
                  "R_wpitch": 8.7, "R_curl": 26.0, "R_fan": 8.0, "R_thumb": 16.0}),
        (0.250, {"pel_z": -0.045, "sp_pitch": 1.0, "R_lower": 30.3, "R_fwd": 45.8, "R_elbow": 73.3, "R_roll": 94.0,
                  "R_wpitch": 3.3, "R_wyaw": 15.2, "R_curl": 14.0, "R_fan": 10.0, "R_thumb": 10.0}),
        (0.330, {"pel_z": -0.045, "sp_pitch": 0.0, "head_pitch": -3.0, "R_lower": 12.3, "R_fwd": 42.9,
                  "R_elbow": 88.8, "R_roll": 95.0, "R_wpitch": -2.8, "R_wyaw": 22.0, "R_curl": 4.0, "R_fan": 12.0,
                  "R_thumb": 8.0}),
        (F(16), {}),
    ]),
    "Cast_EarthSpikes": (F(16), [
        (0.000, {}),
        (0.120, {"sp_pitch": 0.0, "sp_yaw": 6.0, "R_lower": 23.8, "R_fwd": 38.4, "R_elbow": 86.6, "R_roll": -22.3,
                  "R_wpitch": -22.8, "R_wyaw": -18.3, "R_curl": 8.0, "R_fan": 8.0, "R_thumb": 8.0}),
        (0.250, {"pel_z": -0.07, "sp_pitch": 7.0, "sp_yaw": 3.0, "coat_trail": 2.0, "R_lower": 30.6, "R_fwd": 86.6,
                  "R_elbow": 10.8, "R_roll": -14.7, "R_wpitch": -29.0, "R_wyaw": -8.9, "R_curl": 4.0, "R_fan": 12.0,
                  "R_thumb": 8.0}),
        (0.330, {"pel_z": -0.07, "sp_pitch": 7.0, "sp_yaw": 3.0, "R_lower": 32.1, "R_fwd": 87.7, "R_elbow": 8.7,
                  "R_roll": -10.5, "R_wpitch": -31.6, "R_wyaw": -4.7, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0}),
        (F(16), {}),
    ]),
    "Cast_WindBlade": (F(11), [
        (0.000, {}),
        (0.080, {"pel_yaw": -9.0, "sp_yaw": 9.0, "R_lower": 42.5, "R_fwd": 55.1, "R_elbow": 60.3, "R_roll": -16.8,
                  "R_wpitch": -18.5, "R_wyaw": -0.1, "R_curl": 2.0, "R_fan": -6.0, "R_thumb": 20.0}),
        (0.150, {"pel_yaw": -11.0, "sp_yaw": 4.0, "R_lower": 26.6, "R_fwd": 77.9, "R_elbow": 12.8, "R_roll": -11.1,
                  "R_wpitch": -23.8, "R_wyaw": -6.9, "R_curl": 2.0, "R_fan": -6.0, "R_thumb": 20.0}),
        (0.250, {"pel_yaw": -13.0, "sp_yaw": -2.0, "R_lower": 26.4, "R_fwd": 66.3, "R_elbow": 11.7, "R_roll": -6.4,
                  "R_wpitch": -25.8, "R_wyaw": -16.5, "R_curl": 2.0, "R_fan": -6.0, "R_thumb": 20.0}),
        (F(11), {}),
    ]),
    "Cast_Tornado": (F(20), [
        (0.000, {}),
        (0.080, {"sp_yaw": 5.0, "R_lower": 33.3, "R_fwd": 60.1, "R_elbow": 41.9, "R_roll": 29.6, "R_wpitch": 3.4,
                  "R_wyaw": -18.4, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (0.112, {"sp_yaw": 6.4, "R_lower": 27.8, "R_fwd": 73.6, "R_elbow": 25.6, "R_roll": 50.8, "R_wpitch": 9.3,
                  "R_wyaw": -21.4, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (0.144, {"sp_yaw": 8.6, "R_lower": 28.4, "R_fwd": 66.5, "R_elbow": 47.0, "R_roll": 64.5, "R_wpitch": -0.9,
                  "R_wyaw": -23.1, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (0.176, {"sp_yaw": 8.6, "R_lower": 33.0, "R_fwd": 52.0, "R_elbow": 73.1, "R_roll": 73.6, "R_wpitch": -18.6,
                  "R_wyaw": -23.6, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (0.208, {"sp_yaw": 6.4, "R_lower": 31.4, "R_fwd": 43.5, "R_elbow": 79.4, "R_roll": 82.0, "R_wpitch": -29.4,
                  "R_wyaw": -23.3, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (0.240, {"sp_yaw": 5.0, "R_lower": 22.4, "R_fwd": 50.6, "R_elbow": 65.1, "R_roll": 85.2, "R_wpitch": -28.8,
                  "R_wyaw": -23.5, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (0.400, {"sp_yaw": 6.0, "head_pitch": -5.0, "R_lower": -13.6, "R_fwd": 48.4, "R_elbow": 83.2, "R_roll": 68.7,
                  "R_wpitch": -48.3, "R_wyaw": 10.1, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (0.480, {"sp_yaw": 6.0, "head_pitch": -4.0, "R_lower": -10.2, "R_fwd": 48.3, "R_elbow": 84.2, "R_roll": 56.0,
                  "R_wpitch": -58.9, "R_wyaw": 14.1, "R_curl": 80.0, "R_fan": -2.0, "R_thumb": 44.0, "R_ci": -82.0}),
        (F(20), {}),
    ]),
    "Cast_WindBurst": (F(11), [
        (0.000, {}),
        (0.070, {"pel_z": -0.06, "sp_pitch": 3.0, "R_lower": 60.5, "R_fwd": 26.8, "R_elbow": 64.0, "R_curl": 40.0,
                  "R_thumb": 26.0, "L_lower": 70.9, "L_fwd": 7.9, "L_elbow": 66.5, "L_curl": 40.0, "L_thumb": 26.0}),
        (0.200, {"sp_pitch": -2.0, "coat_flare": 6.0, "hair_lag": -3.0, "R_lower": 46.6, "R_fwd": 27.8,
                  "R_elbow": 46.4, "R_roll": -21.0, "R_wpitch": -27.7, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0,
                  "L_lower": 52.8, "L_fwd": 7.8, "L_elbow": 59.3, "L_roll": -17.5, "L_wpitch": -28.8, "L_curl": 4.0,
                  "L_fan": 12.0}),
        (0.240, {"sp_pitch": -1.5, "coat_flare": 5.0, "R_lower": 47.5, "R_fwd": 29.2, "R_elbow": 45.6,
                  "R_roll": -42.3, "R_wpitch": -38.2, "R_curl": 4.0, "R_fan": 12.0, "R_thumb": 8.0, "L_lower": 54.0,
                  "L_fwd": 8.8, "L_elbow": 58.6, "L_roll": -34.8, "L_wpitch": -44.9, "L_curl": 4.0, "L_fan": 12.0}),
        (F(11), {}),
    ]),
    "DisturbMagic": (F(26), [
        (0.000, {}),
        (0.050, {"sp_yaw": 8.0, "R_lower": 53.4, "R_fwd": 26.8, "R_elbow": 65.2, "R_roll": 5.9, "R_wpitch": -26.8,
                  "R_curl": 40.0, "R_thumb": 48.0, "R_cm": 30.0}),
        (0.140, {"sp_yaw": 8.5, "head_pitch": -1.0, "R_lower": 34.7, "R_fwd": 38.6, "R_elbow": 73.3, "R_roll": 11.8,
                  "R_wpitch": -49.9, "R_curl": 4.0, "R_fan": 10.0, "R_thumb": 8.0}),
        (0.400, {"sp_yaw": 8.5, "head_pitch": -1.0, "R_lower": 32.2, "R_fwd": 40.5, "R_elbow": 71.7, "R_roll": 16.2,
                  "R_wpitch": -58.7, "R_fan": 8.0, "R_thumb": 8.0}),
        (0.620, {"sp_yaw": 7.5, "R_lower": 54.1, "R_fwd": 27.8, "R_elbow": 60.1, "R_roll": 16.2, "R_wpitch": -58.2,
                  "R_curl": 8.0, "R_fan": 2.0, "R_thumb": 8.0}),
        (F(26), {}),
    ]),
    "DragonCrush": (F(27), [
        (0.000, {}),
        (0.100, {"pel_y": 0.02, "pel_z": -0.085, "pel_yaw": -16.0, "sp_pitch": 4.0, "sp_yaw": -4.0, "head_yaw": 10.0,
                  "coat_trail": -2.0, "R_lower": 71.3, "R_fwd": 9.1, "R_elbow": 73.8, "R_wpitch": -32.0,
                  "R_curl": 14.0, "R_fan": 4.0, "R_thumb": 10.0, "L_lower": 72.4, "L_fwd": -8.5, "L_elbow": 76.3,
                  "L_curl": 16.0, "L_fan": 2.0, "L_thumb": 10.0}),
        (0.160, {"pel_y": 0.035, "pel_z": -0.11, "pel_yaw": -22.0, "sp_pitch": 5.0, "sp_yaw": -7.0, "head_yaw": 16.0,
                  "coat_trail": -3.0, "L_fy": -0.1, "L_fz": 0.025, "R_lower": 73.6, "R_fwd": 6.9, "R_elbow": 79.2,
                  "R_wpitch": -40.0, "R_curl": 20.0, "R_fan": 2.0, "R_thumb": 12.0, "L_lower": 86.0, "L_fwd": -39.3,
                  "L_elbow": 85.8, "L_curl": 16.0, "L_fan": 2.0, "L_thumb": 10.0}),
        (0.280, {"pel_y": -0.01, "pel_z": -0.13, "pel_yaw": -12.0, "sp_pitch": 8.0, "sp_yaw": -3.0, "head_yaw": 7.0,
                  "coat_trail": 4.0, "L_fy": -0.15, "L_fz": 0.025, "R_lower": 49.0, "R_fwd": 34.5, "R_elbow": 81.0,
                  "R_wpitch": -50.0, "R_curl": 8.0, "R_fan": 8.0, "R_thumb": 8.0, "L_lower": 89.7, "L_fwd": -40.3,
                  "L_elbow": 90.8, "L_curl": 26.0, "L_fan": 2.0, "L_thumb": 14.0}),
        (0.400, {"pel_y": -0.07, "pel_z": -0.16, "pel_yaw": 4.0, "sp_pitch": 12.0, "sp_yaw": 2.0, "head_pitch": 2.0,
                  "coat_trail": 12.0, "coat_flare": 6.0, "hair_lag": 7.0, "L_fy": -0.17, "L_fz": 0.025,
                  "R_lower": 11.5, "R_fwd": 79.0, "R_elbow": 20.0, "R_roll": -6.2, "R_wpitch": -61.0, "R_curl": 4.0,
                  "R_fan": 14.0, "R_thumb": 8.0, "L_lower": 90.4, "L_fwd": -51.8, "L_elbow": 101.5, "L_curl": 34.0,
                  "L_fan": 2.0, "L_thumb": 18.0}),
        (0.450, {"pel_y": -0.072, "pel_z": -0.162, "pel_yaw": 4.0, "sp_pitch": 12.0, "sp_yaw": 2.0,
                  "head_pitch": 2.0, "coat_trail": 11.0, "coat_flare": 6.0, "hair_lag": 7.0, "L_fy": -0.17,
                  "L_fz": 0.025, "R_lower": 9.8, "R_fwd": 84.4, "R_elbow": 10.7, "R_roll": -10.7, "R_wpitch": -62.6,
                  "R_curl": 5.0, "R_fan": 13.0, "R_thumb": 8.0, "L_lower": 90.4, "L_fwd": -51.8, "L_elbow": 101.5,
                  "L_curl": 34.0, "L_fan": 2.0, "L_thumb": 18.0}),
        (0.550, {"pel_y": -0.07, "pel_z": -0.155, "pel_yaw": 4.0, "sp_pitch": 12.0, "sp_yaw": 2.0, "head_pitch": 2.0,
                  "coat_trail": 7.0, "coat_flare": 6.0, "hair_lag": 4.0, "L_fy": -0.17, "L_fz": 0.025,
                  "R_lower": 10.2, "R_fwd": 83.0, "R_elbow": 11.7, "R_roll": -15.3, "R_wpitch": -63.0, "R_fan": 12.0,
                  "R_thumb": 8.0, "L_lower": 90.4, "L_fwd": -51.8, "L_elbow": 101.5, "L_curl": 34.0, "L_fan": 2.0,
                  "L_thumb": 18.0}),
        (0.670, {"pel_y": -0.04, "pel_z": -0.11, "pel_yaw": -4.0, "sp_pitch": 6.0, "sp_yaw": 5.0, "coat_trail": 2.0,
                  "L_fy": -0.17, "L_fz": 0.025, "R_lower": 37.8, "R_fwd": 47.7, "R_elbow": 53.3, "R_roll": -15.3,
                  "R_wpitch": -58.8, "R_curl": 10.0, "R_fan": 4.0, "R_thumb": 8.0, "L_lower": 78.7, "L_fwd": -20.8,
                  "L_elbow": 74.2, "L_curl": 22.4, "L_fan": 1.1, "L_thumb": 13.6}),
        (0.740, {"pel_y": -0.02, "pel_z": -0.075, "pel_yaw": -8.0, "sp_pitch": 3.0, "sp_yaw": 6.0, "L_fy": -0.13,
                  "L_fz": 0.035, "R_lower": 48.2, "R_fwd": 37.6, "R_elbow": 50.8, "R_roll": -8.2, "R_wpitch": -37.0,
                  "R_curl": 8.1, "R_fan": 2.1, "R_thumb": 7.1, "L_lower": 71.8, "L_fwd": -2.7, "L_elbow": 58.2,
                  "L_curl": 15.7, "L_fan": 0.6, "L_thumb": 11.0}),
        (0.820, {"pel_z": -0.055}),
        (F(27), {}),
    ]),
}

O_EVENTS = {
    "Cast_Fireball": {"Release": 0.19}, "Cast_Fireball_Release": {"Release": 0.04},
    "Cast_FlameWave": {"Release": 0.26}, "Cast_Inferno": {"Release": 0.55},
    "Cast_WaterBullet": {"Release": 0.14}, "Cast_WaterDragon": {"Release": 0.45}, "Cast_Flood": {"Release": 0.42},
    "Cast_StoneCannon": {"Release": 0.22}, "Cast_StoneCannon_Release": {"Release": 0.04},
    "Cast_EarthWall": {"Release": 0.25}, "Cast_EarthSpikes": {"Release": 0.25},
    "Cast_WindBlade": {"Release": 0.15}, "Cast_Tornado": {"Release": 0.34}, "Cast_WindBurst": {"Release": 0.08},
    "DisturbMagic": {"Release": 0.06}, "DragonCrush": {"Release": 0.40},
}


def still_hold(P0, period, side="R", fingers=3.0, wrist=2.0):
    """Orsted holding a spell: almost still, a slow finger wave and a slight turn of the wrist."""
    def fn(t):
        w = TAU * (t % period) / period
        P = dict(P0)
        for i, k in enumerate(("ci", "cm", "cr", "cp")):
            P[side + "_" + k] = P0.get(side + "_" + k, 0.0) + fingers * _wave(w, -0.8 * i)
        P[side + "_roll"] = P0.get(side + "_roll", 0.0) + wrist * math.sin(w)
        P["hair_lag"] = P0.get("hair_lag", 0.0) + 0.3 * math.sin(w)
        return P
    return fn


# ============================================================================================================ builders
def _oneshots(table, stance, keyed):
    out = {}
    for name, (duration, keys) in table.items():
        full = [(t, _m(stance, d)) for t, d in keys]
        out[name] = (duration, False, (lambda t, full=full: keyed(full, t, stance)))
    return out


def rudeus(C):
    """Rudeus's clips and events. C is the clips module (its COMBAT stance and keyed interpolation)."""
    clips = _oneshots(R_KEYS, C.COMBAT, C.keyed)
    clips["Cast_Fireball_Hold"] = (F(30), True, fireball_hold(_m(C.COMBAT, FB_HOLD), F(30)))
    clips["Cast_StoneCannon_Hold"] = (F(30), True, stone_hold(_m(C.COMBAT, SCS_HOLD), F(30), tremor=0.9, press=4.0))
    clips["StoneCannon_Hold"] = (F(30), True, stone_hold(_m(C.COMBAT, SC_HOLD), F(30), tremor=1.5, press=5.0))
    clips["Quagmire_Hold"] = (F(30), True, quagmire_hold(_m(C.COMBAT, QG_HOLD), F(30)))
    return clips, {k: dict(v) for k, v in R_EVENTS.items()}


def orsted(guard, keyed):
    """Orsted's own element casts, Disturb Magic and Dragon Crush (his guard in and out)."""
    clips = _oneshots(O_KEYS, guard, keyed)
    clips["Cast_Fireball_Hold"] = (F(18), True, still_hold(_m(guard, OFB_HOLD), F(18)))
    clips["Cast_StoneCannon_Hold"] = (F(18), True, still_hold(_m(guard, OSC_HOLD), F(18), fingers=2.0, wrist=1.5))
    return clips, {k: dict(v) for k, v in O_EVENTS.items()}
